// NOTE: Assertions have been autogenerated by utils/update_mc_test_checks.py UTC_ARGS: --version 6
; REQUIRES: bedrock-registered-target
; RUN: llvm-mc -triple=bedrock -show-encoding < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK-INST,CHECK-ENCODING
; RUN: llvm-mc -triple=bedrock -show-encoding < %s \
; RUN:   | sed '/.text/d' | sed 's/.*encoding: //g' \
; RUN:   | llvm-mc -triple=bedrock -disassemble -show-encoding \
; RUN:   | FileCheck %s --check-prefixes=CHECK-INST,CHECK-ENCODING

nop
// CHECK-INST: nop                                     ; encoding: [0x01]

ret
// CHECK-INST: ret                                     ; encoding: [0x02]

mov.q r1, r2
// CHECK-INST: mov.q	r1, r2                          ; encoding: [0x81,0x12]

mov.l r1, r2
// CHECK-INST: mov.l	r1, r2                          ; encoding: [0x80,0x12]

mov.b r1, r2
// CHECK-INST: mov.b	r1, r2                          ; encoding: [0xa6,0x12]

mov.w r3, r4
// CHECK-INST: mov.w	r3, r4                          ; encoding: [0xa7,0x34]

extsq.b r7, r8
// CHECK-INST: extsq.b	r7, r8                        ; encoding: [0xc2,0x26,0x78]

extsq.w r9, r10
// CHECK-INST: extsq.w	r9, r10                       ; encoding: [0xc2,0x2e,0x9a]

extsq.l r11, r12
// CHECK-INST: extsq.l	r11, r12                      ; encoding: [0xa2,0xbc]

add.q r3, r4
// CHECK-INST: add.q	r3, r4                          ; encoding: [0x83,0x34]

mov.q r5, sp
// CHECK-INST: mov.q	r5, sp                          ; encoding: [0x55]

mov.q sp, r6
// CHECK-INST: mov.q	sp, r6                          ; encoding: [0x66]

push r7
// CHECK-INST: push	r7                              ; encoding: [0x37]

pop r8
// CHECK-INST: pop	r8                              ; encoding: [0x48]

set r0
// CHECK-INST: set	r0                              ; encoding: [0xa0,0x00]

seteq r9
// CHECK-INST: seteq	r9                              ; encoding: [0xa0,0x29]

setnz r1
// CHECK-INST: setne	r1                              ; encoding: [0xa0,0x31]

inc.q r10
// CHECK-INST: inc.q	r10                             ; encoding: [0xa9,0x0a]

revbyte.q r11
// CHECK-INST: revbyte.q	r11                     ; encoding: [0xac,0x3b]

add.q 255, sp
// CHECK-INST: add.q	255, sp                         ; encoding: [0xa3,0xff]

add.q 8, sp
// CHECK-INST: add.q	8, sp                           ; encoding: [0x0e]

jmp -1
// CHECK-INST: jmp	-1                              ; encoding: [0xa4,0xff]

sub.q 1, sp
// CHECK-INST: sub.q	1, sp                           ; encoding: [0xa5,0x01]

sub.q 8, sp
// CHECK-INST: sub.q	8, sp                           ; encoding: [0x0f]

jeq -2
// CHECK-INST: jeq	-2                              ; encoding: [0xb2,0xfe]

jz -2
// CHECK-INST: jeq	-2                              ; encoding: [0xb2,0xfe]

jmp 1000
// CHECK-INST: jmp	1000                            ; encoding: [0xcb,0xbc,0x06,0xe8,0x03]

call r3
// CHECK-INST: call	r3                              ; encoding: [0xc3,0xb4,0x23]

jmp.q r4
// CHECK-INST: jmp.q	r4                              ; encoding: [0xc3,0xb0,0xe4]

inc.b [r1]
// CHECK-INST: inc.b	[r1]                            ; encoding: [0xc3,0x84,0x81]

mov.b r1, [r2]
// CHECK-INST: mov.b	r1, [r2]                        ; encoding: [0xc0,0x00,0x82]

mov.q r1, [r2]
// CHECK-INST: mov.q	r1, [r2]                        ; encoding: [0xc0,0x18,0x82]

mov.q r1, [ds:r2]
// CHECK-INST: mov.q	r1, [ds:r2]                     ; encoding: [0xc4,0x18,0xe3,0x02]

mov.q r1, [r2++]
// CHECK-INST: mov.q	r1, [r2++]                      ; encoding: [0xc4,0x18,0xe3,0x94]

mov.q r1, [--r2]
// CHECK-INST: mov.q	r1, [--r2]                      ; encoding: [0xc4,0x18,0xe3,0x95]

mov.q r1, [r2 + r3]
// CHECK-INST: mov.q	r1, [ds:r2 + r3]                ; encoding: [0xc8,0x18,0xe8,0x82,0x23]

mov.q r1, [r2 + r3++ + 4]
// CHECK-INST: mov.q	r1, [ds:r2 + r3++ + 4]          ; encoding: [0xcc,0x18,0xe4,0x80,0x23,0x04]

mov.q r1, [ds:0 + --r3 - 5]
// CHECK-INST: mov.q	r1, [ds:0 + --r3 - 5]           ; encoding: [0xcc,0x18,0xe4,0x89,0x13,0xfb]

mov.q r1, [sp + r3]
// CHECK-INST: mov.q	r1, [sp + r3]                   ; encoding: [0xc8,0x18,0xe8,0x8a,0x23]

mov.q r1, [pc + r3 + 4]
// CHECK-INST: mov.q	r1, [pc + r3 + 4]               ; encoding: [0xcc,0x18,0xe4,0x8b,0x23,0x04]

adc.q r1, [r2]
// CHECK-INST: adc.q	r1, [r2]                        ; encoding: [0xc7,0xcc,0xe0,0x82]

mov.q [r1], [r2]
// CHECK-INST: mov.q	[r1], [r2]                      ; encoding: [0xc7,0xc4,0xc0,0x82]

rol.q 3, [r8]
// CHECK-INST: rol.q	3, [r8]                         ; encoding: [0xc7,0xd4,0xc1,0x88]

rdseg cs, r5
// CHECK-INST: rdseg	cs, r5                          ; encoding: [0xc3,0xb5,0x05]

invtlb
// CHECK-INST: invtlb                                  ; encoding: [0xc3,0xbc,0x05]
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK-ENCODING: {{.*}}
