// NOTE: Assertions have been autogenerated by utils/update_mc_test_checks.py UTC_ARGS: --version 6
; REQUIRES: bedrock-registered-target
; RUN: llvm-mc -triple=bedrock -mattr=+fptransa -show-encoding < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK-INST,CHECK-ENCODING
; RUN: llvm-mc -triple=bedrock -mattr=+fptransa -show-encoding < %s \
; RUN:   | sed '/.text/d' | sed 's/.*encoding: //g' \
; RUN:   | llvm-mc -triple=bedrock -disassemble -show-encoding \
; RUN:   | FileCheck %s --check-prefixes=CHECK-INST,CHECK-ENCODING

fmadd.s f1, f2, f3
// CHECK-INST: fmadd.s	f1, f2, f3                      ; encoding: [0xc7,0xe6,0x51,0x23]
fmadd.d [r1], f2, f3
// CHECK-INST: fmadd.d	[r1], f2, f3                    ; encoding: [0xcb,0xf2,0x04,0x11,0x81]
fmadd.s f1, [r2], f3
// CHECK-INST: fmadd.s	f1, [r2], f3                    ; encoding: [0xcb,0xf2,0x02,0x09,0x82]
fmsub.d f4, f5, f6
// CHECK-INST: fmsub.d	f4, f5, f6                      ; encoding: [0xc7,0xe6,0xe4,0x56]
fmsub.s [r3 + 8], f5, f6
// CHECK-INST: fmsub.s	[r3 + 8], f5, f6                ; encoding: [0xcf,0xf2,0x00,0xab,0x13,0x08]
fmsub.d f4, [r6], f7
// CHECK-INST: fmsub.d	f4, [r6], f7                    ; encoding: [0xcb,0xf2,0x06,0xa3,0x86]
fnmadd.s f8, f9, f10
// CHECK-INST: fnmadd.s	f8, f9, f10                     ; encoding: [0xc7,0xe6,0x78,0x9a]
fnmadd.d [r7], f9, f10
// CHECK-INST: fnmadd.d	[r7], f9, f10                   ; encoding: [0xcb,0xf2,0x05,0x4d,0x07]
fnmadd.s f8, [r10], f11
// CHECK-INST: fnmadd.s	f8, [r10], f11                  ; encoding: [0xcb,0xf2,0x03,0x45,0x8a]
fnmsub.d f12, f13, f14
// CHECK-INST: fnmsub.d	f12, f13, f14                   ; encoding: [0xc7,0xe7,0x8c,0xde]
fnmsub.s [r11], f13, f14
// CHECK-INST: fnmsub.s	[r11], f13, f14                 ; encoding: [0xcb,0xf2,0x01,0xef,0x0b]
fnmsub.d f12, [r14], f15
// CHECK-INST: fnmsub.d	f12, [r14], f15                 ; encoding: [0xcb,0xf2,0x07,0xe7,0x8e]

facosa.s f0, f1
// CHECK-INST: facosa.s	f0, f1                          ; encoding: [0xc7,0xe7,0x28,0x01]
fasina.d f1, f2
// CHECK-INST: fasina.d	f1, f2                          ; encoding: [0xc7,0xe7,0xab,0x12]
fatana.s f2, f3
// CHECK-INST: fatana.s	f2, f3                          ; encoding: [0xc7,0xe7,0x2c,0x23]
fatanha.d f3, f4
// CHECK-INST: fatanha.d	f3, f4                  ; encoding: [0xc7,0xe7,0xb0,0x34]
fcosa.s f4, f5
// CHECK-INST: fcosa.s	f4, f5                          ; encoding: [0xc7,0xe7,0x20,0x45]
fcosha.d f5, f6
// CHECK-INST: fcosha.d	f5, f6                          ; encoding: [0xc7,0xe7,0xa1,0x56]
fetoxa.s f6, f7
// CHECK-INST: fetoxa.s	f6, f7                          ; encoding: [0xc7,0xe7,0x22,0x67]
fetoxm1a.d f7, f8
// CHECK-INST: fetoxm1a.d	f7, f8                  ; encoding: [0xc7,0xe7,0xa3,0x78]
flog10a.s f8, f9
// CHECK-INST: flog10a.s	f8, f9                  ; encoding: [0xc7,0xe7,0x24,0x89]
flog2a.d f9, f10
// CHECK-INST: flog2a.d	f9, f10                         ; encoding: [0xc7,0xe7,0xa5,0x9a]
flogna.s f10, f11
// CHECK-INST: flogna.s	f10, f11                        ; encoding: [0xc7,0xe7,0x26,0xab]
flognp1a.d f11, f12
// CHECK-INST: flognp1a.d	f11, f12                ; encoding: [0xc7,0xe7,0xa7,0xbc]
fsina.s f12, f13
// CHECK-INST: fsina.s	f12, f13                        ; encoding: [0xc7,0xe7,0x29,0xcd]
fsinha.d f13, f14
// CHECK-INST: fsinha.d	f13, f14                        ; encoding: [0xc7,0xe7,0xaa,0xde]
ftana.s f14, f15
// CHECK-INST: ftana.s	f14, f15                        ; encoding: [0xc7,0xe7,0x2d,0xef]
ftanha.d f15, f0
// CHECK-INST: ftanha.d	f15, f0                         ; encoding: [0xc7,0xe7,0xae,0xf0]
ftentoxa.s f0, f15
// CHECK-INST: ftentoxa.s	f0, f15                 ; encoding: [0xc7,0xe7,0x2f,0x0f]
ftwotoxa.d f15, f1
// CHECK-INST: ftwotoxa.d	f15, f1                 ; encoding: [0xc7,0xe7,0xb1,0xf1]
fsincosa.s f1, f2, f3
// CHECK-INST: fsincosa.s	f1, f2, f3              ; encoding: [0xc7,0xe7,0x11,0x23]
fsincosa.d f4, f5, f6
// CHECK-INST: fsincosa.d	f4, f5, f6              ; encoding: [0xc7,0xe7,0x94,0x56]

fpushp 0
// CHECK-INST: fpushp	0                               ; encoding: [0x20]
fpushp 3
// CHECK-INST: fpushp	3                               ; encoding: [0x23]
fpopp 3
// CHECK-INST: fpopp	3                               ; encoding: [0x2b]
fpopp 0
// CHECK-INST: fpopp	0                               ; encoding: [0x28]
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK-ENCODING: {{.*}}
