// NOTE: Assertions have been autogenerated by utils/update_mc_test_checks.py UTC_ARGS: --version 6
; REQUIRES: bedrock-registered-target
; RUN: llvm-mc -triple=bedrock -show-encoding < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK-INST,CHECK-ENCODING
; RUN: llvm-mc -triple=bedrock -show-encoding < %s \
; RUN:   | sed '/.text/d' | sed 's/.*encoding: //g' \
; RUN:   | llvm-mc -triple=bedrock -disassemble -show-encoding \
; RUN:   | FileCheck %s --check-prefixes=CHECK-INST,CHECK-ENCODING

fmin.s f1, f2
// CHECK-INST: fmin.s	f1, f2                          ; encoding: [0xc2,0xe1,0x12]

fmin.d [r3], f4
// CHECK-INST: fmin.d	[r3], f4                        ; encoding: [0xc7,0xe5,0xca,0x03]

fmax.d f5, f6
// CHECK-INST: fmax.d	f5, f6                          ; encoding: [0xc2,0xe8,0x56]

fmax.s 2, f7
// CHECK-INST: fmax.s	immsf(0x40000000), f7           ; encoding: [0xd7,0xe5,0x43,0xdd,0x00,0x00,0x00,0x40]

fint.s f8, f9
// CHECK-INST: fint.s	f8, f9                          ; encoding: [0xc2,0xc2,0x89]

fint.d [r10 + 4], f11
// CHECK-INST: fint.d	[r10 + 4], f11                  ; encoding: [0xcb,0xe5,0x95,0x9a,0x04]

fint.s f12, [r13]
// CHECK-INST: fint.s	f12, [r13]                      ; encoding: [0xc7,0xe4,0x5e,0x0d]

fintrz.d f14, f15
// CHECK-INST: fintrz.d	f14, f15                        ; encoding: [0xc2,0xcb,0xef]

fintrz.s [sp + 8], f0
// CHECK-INST: fintrz.s	[sp + 8], f0                    ; encoding: [0xcb,0xe5,0x18,0x50,0x08]

fintrz.d f1, [r2]
// CHECK-INST: fintrz.d	f1, [r2]                        ; encoding: [0xc7,0xe4,0xe8,0x82]

fgetexp.s f3, f4
// CHECK-INST: fgetexp.s	f3, f4                  ; encoding: [0xc2,0xc0,0x34]

fgetexp.d [r5], f6
// CHECK-INST: fgetexp.d	[r5], f6                ; encoding: [0xc7,0xe5,0x83,0x05]

fgetman.d f7, f8
// CHECK-INST: fgetman.d	f7, f8                  ; encoding: [0xc2,0xc9,0x78]

fgetman.s 3, f9
// CHECK-INST: fgetman.s	immsf(0x40400000), f9   ; encoding: [0xd7,0xe5,0x0c,0xdd,0x00,0x00,0x40,0x40]

fmod.s f10, f11
// CHECK-INST: fmod.s	f10, f11                        ; encoding: [0xc2,0xe2,0xab]

fmod.d [r12], f13
// CHECK-INST: fmod.d	[r12], f13                      ; encoding: [0xc7,0xe5,0xd6,0x8c]

frem.d f14, f15
// CHECK-INST: frem.d	f14, f15                        ; encoding: [0xc2,0xee,0xef]

frem.s [r0 + 16], f1
// CHECK-INST: frem.s	[r0 + 16], f1                   ; encoding: [0xcb,0xe5,0x70,0x90,0x10]

fscale.s f2, f3
// CHECK-INST: fscale.s	f2, f3                          ; encoding: [0xc2,0x81,0x23]

fscale.d [r4], f5
// CHECK-INST: fscale.d	[r4], f5                        ; encoding: [0xc7,0xe4,0x8a,0x84]

fcopysign.d f6, f7, f8
// CHECK-INST: fcopysign.d	f6, f7, f8              ; encoding: [0xc7,0xe6,0xc6,0x78]

fbndii.s f1, f2, f3
// CHECK-INST: fbndii.s	f1, f2, f3                      ; encoding: [0xcb,0xf3,0x28,0x01,0x23]

fbndii.d f4, [r5 + 8], f6
// CHECK-INST: fbndii.d	f4, [r5 + 8], f6                ; encoding: [0xcf,0xf3,0x20,0xa3,0x15,0x08]

fbndii.s [r7 + 1], f8, [r9 + 2]
// CHECK-INST: fbndii.s	[r7 + 1], f8, [r9 + 2]          ; encoding: [0xd3,0xf3,0x02,0x0b,0x99,0x01,0x02]

fbndix.d f10, f11, f12
// CHECK-INST: fbndix.d	f10, f11, f12                   ; encoding: [0xcb,0xf3,0x28,0x3a,0xbc]

fbndix.s f13, 1, f14
// CHECK-INST: fbndix.s	f13, immsf(0x3f800000), f14     ; encoding: [0xdb,0xf3,0x21,0x6f,0x5d,0x00,0x00,0x80,0x3f]

fbndix.d [sp + 16], f15, [r0]
// CHECK-INST: fbndix.d	[sp + 16], f15, [r0]            ; encoding: [0xcf,0xf3,0x0f,0xe8,0x00,0x10]

fbndxi.s f1, f2, f3
// CHECK-INST: fbndxi.s	f1, f2, f3                      ; encoding: [0xcb,0xf3,0x28,0x41,0x23]

fbndxi.d f4, [r5], f6
// CHECK-INST: fbndxi.d	f4, [r5], f6                    ; encoding: [0xcb,0xf3,0x22,0xa3,0x05]

fbndxi.s 0, f7, [r8 + 4]
// CHECK-INST: fbndxi.s	immsf(0x00000000), f7, [r8 + 4] ; encoding: [0xdf,0xf3,0x11,0xee,0x98,0x00,0x00,0x00,0x00,0x04]

fbndxx.d f9, f10, f11
// CHECK-INST: fbndxx.d	f9, f10, f11                    ; encoding: [0xcb,0xf3,0x28,0x79,0xab]

fbndxx.s f12, [r13], f14
// CHECK-INST: fbndxx.s	f12, [r13], f14                 ; encoding: [0xcb,0xf3,0x23,0x67,0x0d]

fbndxx.d [r15], f0, 2
// CHECK-INST: fbndxx.d	[r15], f0, immdf(0x4000000000000000) ; encoding: [0xeb,0xf3,0x1c,0x07,0xde,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x40]
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK-ENCODING: {{.*}}
