// NOTE: Assertions have been autogenerated by utils/update_mc_test_checks.py UTC_ARGS: --version 6
; REQUIRES: bedrock-registered-target
; RUN: llvm-mc -triple=bedrock -show-encoding < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK-INST,CHECK-ENCODING
; RUN: llvm-mc -triple=bedrock -show-encoding < %s \
; RUN:   | sed '/.text/d' | sed 's/.*encoding: //g' \
; RUN:   | llvm-mc -triple=bedrock -disassemble -show-encoding \
; RUN:   | FileCheck %s --check-prefixes=CHECK-INST,CHECK-ENCODING

fmov.s f0, f1
// CHECK-INST: fmov.s	f0, f1                          ; encoding: [0xc2,0xe3,0x01]

fmov.d f2, f3
// CHECK-INST: fmov.d	f2, f3                          ; encoding: [0xc2,0xeb,0x23]

fadd.s f4, f5
// CHECK-INST: fadd.s	f4, f5                          ; encoding: [0xc2,0x82,0x45]

fadd.d f6, f7
// CHECK-INST: fadd.d	f6, f7                          ; encoding: [0xc2,0x8a,0x67]

fsub.s f8, f9
// CHECK-INST: fsub.s	f8, f9                          ; encoding: [0xc2,0x84,0x89]

fsub.d f10, f11
// CHECK-INST: fsub.d	f10, f11                        ; encoding: [0xc2,0x8c,0xab]

fmul.s f12, f13
// CHECK-INST: fmul.s	f12, f13                        ; encoding: [0xc2,0xe4,0xcd]

fmul.d f14, f15
// CHECK-INST: fmul.d	f14, f15                        ; encoding: [0xc2,0xec,0xef]

fdiv.s f1, f2
// CHECK-INST: fdiv.s	f1, f2                          ; encoding: [0xc2,0xa4,0x12]

fdiv.d f3, f4
// CHECK-INST: fdiv.d	f3, f4                          ; encoding: [0xc2,0xac,0x34]

fabs.s f4, f5
// CHECK-INST: fabs.s	f4, f5                          ; encoding: [0xc2,0x80,0x45]

fneg.d f5, f6
// CHECK-INST: fneg.d	f5, f6                          ; encoding: [0xc2,0xed,0x56]

fsqrt.s f6, f7
// CHECK-INST: fsqrt.s	f6, f7                          ; encoding: [0xc2,0x83,0x67]

fround.d f7, f8
// CHECK-INST: fround.d	f7, f8                          ; encoding: [0xc2,0xef,0x78]

ftrunc.s f8, f9
// CHECK-INST: ftrunc.s	f8, f9                          ; encoding: [0xc2,0x85,0x89]

fceil.d f9, f10
// CHECK-INST: fceil.d	f9, f10                         ; encoding: [0xc2,0x8e,0x9a]

ffloor.s f10, f11
// CHECK-INST: ffloor.s	f10, f11                        ; encoding: [0xc2,0xa7,0xab]
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK-ENCODING: {{.*}}
