// NOTE: Assertions have been autogenerated by utils/update_mc_test_checks.py UTC_ARGS: --version 6
; REQUIRES: bedrock-registered-target
; RUN: llvm-mc -triple=bedrock -show-encoding < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK-INST,CHECK-ENCODING
; RUN: llvm-mc -triple=bedrock -show-encoding < %s \
; RUN:   | sed '/.text/d' | sed 's/.*encoding: //g' \
; RUN:   | llvm-mc -triple=bedrock -disassemble -show-encoding \
; RUN:   | FileCheck %s --check-prefixes=CHECK-INST,CHECK-ENCODING

fcmp.s f1, f2
// CHECK-INST: fcmp.s	f1, f2                          ; encoding: [0xc2,0x87,0x12]

fcmp.d [r3 + 4], f4
// CHECK-INST: fcmp.d	[r3 + 4], f4                    ; encoding: [0xcb,0xe4,0xba,0x13,0x04]

ftest.s f5
// CHECK-INST: ftest.s	f5                              ; encoding: [0xc3,0xb2,0x15]

ftest.d [r6]
// CHECK-INST: ftest.d	[r6]                            ; encoding: [0xc7,0xd8,0x00,0x86]

fclass.s f7, r8
// CHECK-INST: fclass.s	f7, r8                          ; encoding: [0xc7,0xe3,0x80,0x78]

fmoveq f9, f10
// CHECK-INST: fmoveq	f9, f10                         ; encoding: [0xc7,0xe2,0x82,0x9a]

fmovne.s [r1], f2
// CHECK-INST: fmovne.s	[r1], f2                        ; encoding: [0xc7,0xe0,0x19,0x01]

fmovvc.d f3, [r4 + 8]
// CHECK-INST: fmovvc.d	f3, [r4 + 8]                    ; encoding: [0xcb,0xe1,0xc9,0x94,0x08]
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK-ENCODING: {{.*}}
