// NOTE: Assertions have been autogenerated by utils/update_mc_test_checks.py UTC_ARGS: --version 6
; REQUIRES: bedrock-registered-target
; RUN: llvm-mc -triple=bedrock -show-encoding < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK-INST,CHECK-ENCODING
; RUN: llvm-mc -triple=bedrock -show-encoding < %s \
; RUN:   | sed '/.text/d' | sed 's/.*encoding: //g' \
; RUN:   | llvm-mc -triple=bedrock -disassemble -show-encoding \
; RUN:   | FileCheck %s --check-prefixes=CHECK-INST,CHECK-ENCODING

fclr f15
// CHECK-INST: fclr	f15                             ; encoding: [0xc3,0xb6,0x0f]

fxchg f1, f14
// CHECK-INST: fxchg	f1, f14                         ; encoding: [0xc2,0xa0,0x1e]

fmov.s [r1], f2
// CHECK-INST: fmov.s	[r1], f2                        ; encoding: [0xc7,0xe5,0x59,0x01]

fmov.d f3, [r4 + 8]
// CHECK-INST: fmov.d	f3, [r4 + 8]                    ; encoding: [0xcb,0xe4,0xf1,0x94,0x08]

// FEA reserves scalar [sp] selector 0x58; use stack_pointer_disp8s + zero.
fmov.d f3, [sp]
// CHECK-INST: fmov.d	f3, [sp + 0]                    ; encoding: [0xcb,0xe4,0xf1,0xd0,0x00]

fadd.s 1, f4
// CHECK-INST: fadd.s	immsf(0x3f800000), f4           ; encoding: [0xd7,0xe4,0x12,0x5d,0x00,0x00,0x80,0x3f]

// Numeric FEA sources carry exact IEEE 754 payloads selected by their width.
fadd.s 1.5, f4
// CHECK-INST: fadd.s	immsf(0x3fc00000), f4           ; encoding: [0xd7,0xe4,0x12,0x5d,0x00,0x00,0xc0,0x3f]

fadd.d 1.5, f4
// CHECK-INST: fadd.d	immdf(0x3ff8000000000000), f4   ; encoding: [0xe7,0xe4,0x92,0x5e,0x00,0x00,0x00,0x00,0x00,0x00,0xf8,0x3f]

// The encoded immediate format is independent of the instruction operation size.
fadd.d immsf(0x3fc00000), f4
// CHECK-INST: fadd.d	immsf(0x3fc00000), f4           ; encoding: [0xd7,0xe4,0x92,0x5d,0x00,0x00,0xc0,0x3f]

fsub.d [sp + 16], f5
// CHECK-INST: fsub.d	[sp + 16], f5                   ; encoding: [0xcb,0xe4,0xa2,0xd0,0x10]

fmul.s [r6], f7
// CHECK-INST: fmul.s	[r6], f7                        ; encoding: [0xc7,0xe5,0x63,0x86]

fdiv.d [r8 - 4], f9
// CHECK-INST: fdiv.d	[r8 - 4], f9                    ; encoding: [0xcb,0xe4,0xe4,0x98,0xfc]

fabs.s [r10], f11
// CHECK-INST: fabs.s	[r10], f11                      ; encoding: [0xc7,0xe4,0x05,0x8a]

fabs.d f12, [r13]
// CHECK-INST: fabs.d	f12, [r13]                      ; encoding: [0xc7,0xe4,0xc6,0x0d]

fneg.d [r14], f15
// CHECK-INST: fneg.d	[r14], f15                      ; encoding: [0xc7,0xe5,0xef,0x8e]

fneg.s f0, [r1 + 2]
// CHECK-INST: fneg.s	f0, [r1 + 2]                    ; encoding: [0xcb,0xe5,0x20,0x11,0x02]

fsqrt.s [r2], f3
// CHECK-INST: fsqrt.s	[r2], f3                        ; encoding: [0xc7,0xe4,0x19,0x82]

fsqrt.d f4, [sp + 24]
// CHECK-INST: fsqrt.d	f4, [sp + 24]                   ; encoding: [0xcb,0xe5,0xb2,0x50,0x18]

fround.d [r5], f6
// CHECK-INST: fround.d	[r5], f6                        ; encoding: [0xc7,0xe5,0xfb,0x05]

fround.s f7, [r8]
// CHECK-INST: fround.s	f7, [r8]                        ; encoding: [0xc7,0xe5,0x2b,0x88]

ftrunc.s [r9], f10
// CHECK-INST: ftrunc.s	[r9], f10                       ; encoding: [0xc7,0xe4,0x2d,0x09]

ftrunc.d f11, [r12 + 32]
// CHECK-INST: ftrunc.d	f11, [r12 + 32]                 ; encoding: [0xcb,0xe5,0xbd,0x9c,0x20]

fceil.d [r13], f14
// CHECK-INST: fceil.d	[r13], f14                      ; encoding: [0xc7,0xe4,0xb7,0x0d]

fceil.s f15, [r0]
// CHECK-INST: fceil.s	f15, [r0]                       ; encoding: [0xc7,0xe4,0x4f,0x80]

ffloor.s [r1 + 1], f2
// CHECK-INST: ffloor.s	[r1 + 1], f2                    ; encoding: [0xcb,0xe4,0x79,0x11,0x01]

ffloor.d f3, [r4]
// CHECK-INST: ffloor.d	f3, [r4]                        ; encoding: [0xc7,0xe4,0xd1,0x84]
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK-ENCODING: {{.*}}
