// NOTE: Assertions have been autogenerated by utils/update_mc_test_checks.py UTC_ARGS: --version 6
; REQUIRES: bedrock-registered-target
; RUN: llvm-mc -triple=bedrock -show-encoding < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK-INST,CHECK-ENCODING
; RUN: llvm-mc -triple=bedrock -show-encoding < %s \
; RUN:   | sed '/.text/d' | sed 's/.*encoding: //g' \
; RUN:   | llvm-mc -triple=bedrock -disassemble -show-encoding \
; RUN:   | FileCheck %s --check-prefixes=CHECK-INST,CHECK-ENCODING

fcvt.s f1, f2
// CHECK-INST: fcvt.s	f1, f2                          ; encoding: [0xc2,0xa2,0x12]

fcvt.d f3, r4
// CHECK-INST: fcvt.d	f3, r4                          ; encoding: [0xc7,0xe3,0xca,0x34]

fcvt.s r5, f6
// CHECK-INST: fcvt.s	r5, f6                          ; encoding: [0xc7,0xe2,0x0a,0x56]

fcvtu.d f7, f8
// CHECK-INST: fcvtu.d	f7, f8                          ; encoding: [0xc2,0xab,0x78]

fcvtu.s f9, r10
// CHECK-INST: fcvtu.s	f9, r10                         ; encoding: [0xc7,0xe3,0x8b,0x9a]

fcvtu.d r11, f12
// CHECK-INST: fcvtu.d	r11, f12                        ; encoding: [0xc7,0xe2,0x4b,0xbc]
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK-ENCODING: {{.*}}
