// NOTE: Assertions have been autogenerated by utils/update_mc_test_checks.py UTC_ARGS: --version 6
; REQUIRES: bedrock-registered-target
; RUN: llvm-mc -triple=bedrock -show-encoding < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK-INST,CHECK-ENCODING
; RUN: llvm-mc -triple=bedrock -show-encoding < %s \
; RUN:   | sed '/.text/d' | sed 's/.*encoding: //g' \
; RUN:   | llvm-mc -triple=bedrock -disassemble -show-encoding \
; RUN:   | FileCheck %s --check-prefixes=CHECK-INST,CHECK-ENCODING

add.b -1, [r1]
// CHECK-INST: add.b	-1, [r1]                        ; encoding: [0xc7,0x80,0x81,0xff]

add.w 256, [r2 + 4]
// CHECK-INST: add.w	256, [r2 + 4]                   ; encoding: [0xcf,0x89,0x12,0x04,0x00,0x01]

add.l 65536, [r3]
// CHECK-INST: add.l	65536, [r3]                     ; encoding: [0xd3,0x91,0x83,0x00,0x00,0x01,0x00]

add.q 4294967296, [sp + 8]
// CHECK-INST: add.q	4294967296, [sp + 8]            ; encoding: [0xe7,0xa0,0x50,0x08,0x00,0x00,0x00,0x00,0x01,0x00,0x00,0x00]

sub.b 7, [r4]
// CHECK-INST: sub.b	7, [r4]                         ; encoding: [0xcb,0xd8,0x02,0x04,0x07]

sub.w -129, [r5]
// CHECK-INST: sub.w	-129, [r5]                      ; encoding: [0xcf,0xd8,0x04,0x85,0x7f,0xff]

sub.l -32769, [r6 + 1]
// CHECK-INST: sub.l	-32769, [r6 + 1]                ; encoding: [0xdb,0xd8,0x06,0x16,0x01,0xff,0x7f,0xff,0xff]

sub.q -2147483649, [r7]
// CHECK-INST: sub.q	-2147483649, [r7]               ; encoding: [0xe3,0xa7,0x87,0xff,0xff,0xff,0x7f,0xff,0xff,0xff,0xff]

and.b 127, [r8]
// CHECK-INST: and.b	127, [r8]                       ; encoding: [0xc7,0x82,0x08,0x7f]

and.w 4660, [r9]
// CHECK-INST: and.w	4660, [r9]                      ; encoding: [0xcb,0x8a,0x89,0x34,0x12]

and.l 305419896, [r10]
// CHECK-INST: and.l	305419896, [r10]                ; encoding: [0xd3,0x93,0x0a,0x78,0x56,0x34,0x12]

and.q 4294967297, [r11 + 2]
// CHECK-INST: and.q	4294967297, [r11 + 2]           ; encoding: [0xe7,0xa0,0x9b,0x02,0x01,0x00,0x00,0x00,0x01,0x00,0x00,0x00]

or.b -128, [r12]
// CHECK-INST: or.b	-128, [r12]                     ; encoding: [0xc7,0x86,0x8c,0x80]

or.w 128, [r13]
// CHECK-INST: or.w	128, [r13]                      ; encoding: [0xcb,0x8f,0x0d,0x80,0x00]

or.l 32768, [r14 + 16]
// CHECK-INST: or.l	32768, [r14 + 16]               ; encoding: [0xd7,0x97,0x9e,0x10,0x00,0x80,0x00,0x00]

or.q 2147483648, [r15]
// CHECK-INST: or.q	2147483648, [r15]               ; encoding: [0xe3,0xa3,0x8f,0x00,0x00,0x00,0x80,0x00,0x00,0x00,0x00]

xor.b 1, [r0 + 3]
// CHECK-INST: xor.b	1, [r0 + 3]                     ; encoding: [0xcf,0xd8,0x08,0x10,0x03,0x01]

xor.w -256, [r1]
// CHECK-INST: xor.w	-256, [r1]                      ; encoding: [0xcf,0xd8,0x0a,0x81,0x00,0xff]

xor.l -65536, [r2]
// CHECK-INST: xor.l	-65536, [r2]                    ; encoding: [0xd7,0xd8,0x0c,0x02,0x00,0x00,0xff,0xff]

xor.q -4294967296, [r3 + 32]
// CHECK-INST: xor.q	-4294967296, [r3 + 32]          ; encoding: [0xe7,0xa9,0x13,0x20,0x00,0x00,0x00,0x00,0xff,0xff,0xff,0xff]
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK-ENCODING: {{.*}}
