// NOTE: Assertions have been autogenerated by utils/update_mc_test_checks.py UTC_ARGS: --version 6
; REQUIRES: bedrock-registered-target
; RUN: llvm-mc -triple=bedrock -show-encoding < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK-INST,CHECK-ENCODING
; RUN: llvm-mc -triple=bedrock -show-encoding < %s \
; RUN:   | sed '/.text/d' | sed 's/.*encoding: //g' \
; RUN:   | llvm-mc -triple=bedrock -disassemble -show-encoding \
; RUN:   | FileCheck %s --check-prefixes=CHECK-INST,CHECK-ENCODING

eret
// CHECK-INST: eret                                    ; encoding: [0x04]

syscall
// CHECK-INST: syscall                                 ; encoding: [0x05]

push cs
// CHECK-INST: push	cs                              ; encoding: [0x0d]

push ds
// CHECK-INST: push	ds                              ; encoding: [0xae,0x08]

push gs5
// CHECK-INST: push	gs5                             ; encoding: [0xae,0x0f]

pop ss
// CHECK-INST: pop	ss                              ; encoding: [0xae,0x11]

pop gs5
// CHECK-INST: pop	gs5                             ; encoding: [0xae,0x17]

rdseg ds, r1
// CHECK-INST: rdseg	ds, r1                          ; encoding: [0xc3,0xbf,0x81]

rdseg gs5, r2
// CHECK-INST: rdseg	gs5, r2                         ; encoding: [0xc3,0xbf,0xf2]

rdseg cs, r3
// CHECK-INST: rdseg	cs, r3                          ; encoding: [0xc3,0xb5,0x03]

wrseg r4, gs5
// CHECK-INST: wrseg	r4, gs5                         ; encoding: [0xc3,0xbf,0x74]

call [r1]
// CHECK-INST: call	[r1]                            ; encoding: [0xc3,0xa1,0x01]

callne [r2]
// CHECK-INST: callne	[r2]                            ; encoding: [0xc7,0xd8,0x81,0x82]

jmp.l [r3]
// CHECK-INST: jmp.l	[r3]                            ; encoding: [0xc3,0x95,0x03]

jmp.q [r4]
// CHECK-INST: jmp.q	[r4]                            ; encoding: [0xc3,0x9d,0x04]

jeq.l [r5]
// CHECK-INST: jeq.l	[r5]                            ; encoding: [0xc7,0xd8,0x91,0x05]

jne.q [r6]
// CHECK-INST: jne.q	[r6]                            ; encoding: [0xc7,0xd8,0x99,0x86]

fmovcr.s 1, f2
// CHECK-INST: fmovcr.s	1, f2                           ; encoding: [0xcb,0xb2,0x02,0x01,0x00]

fmovcr.d 65535, f15
// CHECK-INST: fmovcr.d	65535, f15                      ; encoding: [0xcb,0xb2,0x4f,0xff,0xff]
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK-ENCODING: {{.*}}
