# NOTE: Generated by spec/isa/tools/gen_llvm_vector_catalog.py.
# RUN: llvm-mc -triple=bedrock -mattr=+vector,+fpu -filetype=obj %s -o %t
# RUN: llvm-objdump -d --no-show-raw-insn %t | FileCheck %s

# CHECK: bpall.b{{[ \t]+}}p0, 1
# long.bpall.v28
bpall.b p0, 1
# CHECK-NEXT: bpall.b{{[ \t]+}}p0, [r3]
# xxlong.bpall.v238
bpall.b p0, [r3]
# CHECK-NEXT: bpany{{[ \t]+}}p0, 1
# long.bpany.v26
bpany p0, 1
# CHECK-NEXT: bpany{{[ \t]+}}p0, [r3]
# xxlong.bpany.v236
bpany p0, [r3]
# CHECK-NEXT: bpnone{{[ \t]+}}p0, 1
# long.bpnone.v27
bpnone p0, 1
# CHECK-NEXT: bpnone{{[ \t]+}}p0, [r3]
# xxlong.bpnone.v237
bpnone p0, [r3]
# CHECK-NEXT: pand{{[ \t]+}}p0, p1
# long.pand.v9
pand p0, p1
# CHECK-NEXT: pcount.b{{[ \t]+}}p0, r1
# long.pcount.v8
pcount.b p0, r1
# CHECK-NEXT: pfalse{{[ \t]+}}p0
# long.pfalse.v24
pfalse p0
# CHECK-NEXT: pfirst.b{{[ \t]+}}p0, r1
# long.pfirst.v6
pfirst.b p0, r1
# CHECK-NEXT: phead.b{{[ \t]+}}r1, p0
# long.phead.v4
phead.b r1, p0
# CHECK-NEXT: plast.b{{[ \t]+}}p0, r1
# long.plast.v7
plast.b p0, r1
# CHECK-NEXT: ploop.b{{[ \t]+}}r1, r2, p0, [r3]
# xxlong.ploop.v233
ploop.b r1, r2, p0, [r3]
# CHECK-NEXT: pmov{{[ \t]+}}[r3], p0
# xxlong.pmov.v234
pmov [r3], p0
# CHECK-NEXT: pmov{{[ \t]+}}p0, [r3]
# xxlong.pmov.v235
pmov p0, [r3]
# CHECK-NEXT: pnot{{[ \t]+}}p0
# long.pnot.v25
pnot p0
# CHECK-NEXT: por{{[ \t]+}}p0, p1
# long.por.v10
por p0, p1
# CHECK-NEXT: ppackhi.w{{[ \t]+}}p0, p1
# long.ppackhi.v15
ppackhi.w p0, p1
# CHECK-NEXT: ppacklo.w{{[ \t]+}}p0, p1
# long.ppacklo.v14
ppacklo.w p0, p1
# CHECK-NEXT: pperm.b{{[ \t]+}}v1, p0
# long.pperm.v44
pperm.b v1, p0
# CHECK-NEXT: psel{{[ \t]+}}p0, p1, p2
# extralong.psel.v129
psel p0, p1, p2
# CHECK-NEXT: pslice.b{{[ \t]+}}p0, 1, p1
# extralong.pslice.v136
pslice.b p0, 1, p1
# CHECK-NEXT: pslidedn.b{{[ \t]+}}1, p0
# long.pslidedn.v46
pslidedn.b 1, p0
# CHECK-NEXT: pslideup.b{{[ \t]+}}1, p0
# long.pslideup.v45
pslideup.b 1, p0
# CHECK-NEXT: ptail.b{{[ \t]+}}r1, p0
# long.ptail.v5
ptail.b r1, p0
# CHECK-NEXT: ptrnhi.b{{[ \t]+}}p0, p1, p2
# extralong.ptrnhi.v135
ptrnhi.b p0, p1, p2
# CHECK-NEXT: ptrnlo.b{{[ \t]+}}p0, p1, p2
# extralong.ptrnlo.v134
ptrnlo.b p0, p1, p2
# CHECK-NEXT: ptrue.b{{[ \t]+}}p0
# long.ptrue.v23
ptrue.b p0
# CHECK-NEXT: punpkhi.b{{[ \t]+}}p0, p1
# long.punpkhi.v13
punpkhi.b p0, p1
# CHECK-NEXT: punpklo.b{{[ \t]+}}p0, p1
# long.punpklo.v12
punpklo.b p0, p1
# CHECK-NEXT: puziphi.b{{[ \t]+}}p0, p1, p2
# extralong.puziphi.v133
puziphi.b p0, p1, p2
# CHECK-NEXT: puziplo.b{{[ \t]+}}p0, p1, p2
# extralong.puziplo.v132
puziplo.b p0, p1, p2
# CHECK-NEXT: pxor{{[ \t]+}}p0, p1
# long.pxor.v11
pxor p0, p1
# CHECK-NEXT: pziphi.b{{[ \t]+}}p0, p1, p2
# extralong.pziphi.v131
pziphi.b p0, p1, p2
# CHECK-NEXT: pziplo.b{{[ \t]+}}p0, p1, p2
# extralong.pziplo.v130
pziplo.b p0, p1, p2
# CHECK-NEXT: vabs.b{{[ \t]+}}p0, v1
# long.vabs.v30
vabs.b p0, v1
# CHECK-NEXT: vabs.b{{[ \t]+}}p0, [r3], v1
# xxlong.vabs.v186
vabs.b p0, [r3], v1
# CHECK-NEXT: vabs.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vabs.v187
vabs.b p0, v1, [r3]
# CHECK-NEXT: vadd.b{{[ \t]+}}p0, v1, v2
# extralong.vadd.v50
vadd.b p0, v1, v2
# CHECK-NEXT: vadd.b{{[ \t]+}}p0, [r3], v1
# xxlong.vadd.v140
vadd.b p0, [r3], v1
# CHECK-NEXT: vadd.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vadd.v141
vadd.b p0, v1, [r3]
# CHECK-NEXT: vand.b{{[ \t]+}}p0, v1, v2
# extralong.vand.v53
vand.b p0, v1, v2
# CHECK-NEXT: vand.b{{[ \t]+}}p0, [r3], v1
# xxlong.vand.v146
vand.b p0, [r3], v1
# CHECK-NEXT: vand.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vand.v147
vand.b p0, v1, [r3]
# CHECK-NEXT: vceil.h{{[ \t]+}}p0, v1
# long.vceil.v42
vceil.h p0, v1
# CHECK-NEXT: vceil.h{{[ \t]+}}p0, [r3], v1
# xxlong.vceil.v210
vceil.h p0, [r3], v1
# CHECK-NEXT: vceil.h{{[ \t]+}}p0, v1, [r3]
# xxlong.vceil.v211
vceil.h p0, v1, [r3]
# CHECK-NEXT: vclass.h{{[ \t]+}}p0, v1
# long.vclass.v43
vclass.h p0, v1
# CHECK-NEXT: vclass.h{{[ \t]+}}p0, [r3], v1
# xxlong.vclass.v212
vclass.h p0, [r3], v1
# CHECK-NEXT: vclass.h{{[ \t]+}}p0, v1, [r3]
# xxlong.vclass.v213
vclass.h p0, v1, [r3]
# CHECK-NEXT: vclr{{[ \t]+}}v1
# long.vclr.v16
vclr v1
# CHECK-NEXT: vcls.b{{[ \t]+}}p0, v1
# long.vcls.v34
vcls.b p0, v1
# CHECK-NEXT: vcls.b{{[ \t]+}}p0, [r3], v1
# xxlong.vcls.v194
vcls.b p0, [r3], v1
# CHECK-NEXT: vcls.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vcls.v195
vcls.b p0, v1, [r3]
# CHECK-NEXT: vclz.b{{[ \t]+}}p0, v1
# long.vclz.v32
vclz.b p0, v1
# CHECK-NEXT: vclz.b{{[ \t]+}}p0, [r3], v1
# xxlong.vclz.v190
vclz.b p0, [r3], v1
# CHECK-NEXT: vclz.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vclz.v191
vclz.b p0, v1, [r3]
# CHECK-NEXT: vcmpeq.b{{[ \t]+}}p0, v1, v2, p1
# extralong.vcmpcc.v47.integer
vcmpeq.b p0, v1, v2, p1
# CHECK-NEXT: vcmpeq.h{{[ \t]+}}p0, v1, v2, p1
# extralong.vcmpcc.v47.fp
vcmpeq.h p0, v1, v2, p1
# CHECK-NEXT: vcmpeq.b{{[ \t]+}}p0, v1, [r3], p1
# xxlong.vcmpcc.v230.integer
vcmpeq.b p0, v1, [r3], p1
# CHECK-NEXT: vcmpeq.h{{[ \t]+}}p0, v1, [r3], p1
# xxlong.vcmpcc.v230.fp
vcmpeq.h p0, v1, [r3], p1
# CHECK-NEXT: vcopysign.h{{[ \t]+}}p0, v1, v2
# extralong.vcopysign.v71
vcopysign.h p0, v1, v2
# CHECK-NEXT: vcopysign.h{{[ \t]+}}p0, [r3], v1
# xxlong.vcopysign.v182
vcopysign.h p0, [r3], v1
# CHECK-NEXT: vcopysign.h{{[ \t]+}}p0, v1, [r3]
# xxlong.vcopysign.v183
vcopysign.h p0, v1, [r3]
# CHECK-NEXT: vcts.b{{[ \t]+}}p0, v1
# long.vcts.v35
vcts.b p0, v1
# CHECK-NEXT: vcts.b{{[ \t]+}}p0, [r3], v1
# xxlong.vcts.v196
vcts.b p0, [r3], v1
# CHECK-NEXT: vcts.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vcts.v197
vcts.b p0, v1, [r3]
# CHECK-NEXT: vctz.b{{[ \t]+}}p0, v1
# long.vctz.v33
vctz.b p0, v1
# CHECK-NEXT: vctz.b{{[ \t]+}}p0, [r3], v1
# xxlong.vctz.v192
vctz.b p0, [r3], v1
# CHECK-NEXT: vctz.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vctz.v193
vctz.b p0, v1, [r3]
# CHECK-NEXT: vcvtd.h{{[ \t]+}}p0, v1, v2
# extralong.vcvtd.v82
vcvtd.h p0, v1, v2
# CHECK-NEXT: vcvtd.l{{[ \t]+}}p0, v1, v2
# extralong.vcvtd.v85
vcvtd.l p0, v1, v2
# CHECK-NEXT: vcvth.s{{[ \t]+}}p0, v1, v2
# extralong.vcvth.v99
vcvth.s p0, v1, v2
# CHECK-NEXT: vcvth.l{{[ \t]+}}p0, v1, v2
# extralong.vcvth.v100
vcvth.l p0, v1, v2
# CHECK-NEXT: vcvtl.h{{[ \t]+}}p0, v1, v2
# extralong.vcvtl.v87
vcvtl.h p0, v1, v2
# CHECK-NEXT: vcvtq.h{{[ \t]+}}p0, v1, v2
# extralong.vcvtq.v89
vcvtq.h p0, v1, v2
# CHECK-NEXT: vcvts.h{{[ \t]+}}p0, v1, v2
# extralong.vcvts.v81
vcvts.h p0, v1, v2
# CHECK-NEXT: vcvts.l{{[ \t]+}}p0, v1, v2
# extralong.vcvts.v83
vcvts.l p0, v1, v2
# CHECK-NEXT: vcvtud.l{{[ \t]+}}p0, v1, v2
# extralong.vcvtud.v86
vcvtud.l p0, v1, v2
# CHECK-NEXT: vcvtuh.l{{[ \t]+}}p0, v1, v2
# extralong.vcvtuh.v101
vcvtuh.l p0, v1, v2
# CHECK-NEXT: vcvtul.h{{[ \t]+}}p0, v1, v2
# extralong.vcvtul.v88
vcvtul.h p0, v1, v2
# CHECK-NEXT: vcvtuq.h{{[ \t]+}}p0, v1, v2
# extralong.vcvtuq.v90
vcvtuq.h p0, v1, v2
# CHECK-NEXT: vcvtus.l{{[ \t]+}}p0, v1, v2
# extralong.vcvtus.v84
vcvtus.l p0, v1, v2
# CHECK-NEXT: vdiv.h{{[ \t]+}}p0, v1, v2
# extralong.vdiv.v70
vdiv.h p0, v1, v2
# CHECK-NEXT: vdiv.h{{[ \t]+}}p0, [r3], v1
# xxlong.vdiv.v180
vdiv.h p0, [r3], v1
# CHECK-NEXT: vdiv.h{{[ \t]+}}p0, v1, [r3]
# xxlong.vdiv.v181
vdiv.h p0, v1, [r3]
# CHECK-NEXT: vdup.b{{[ \t]+}}r1, v1
# long.vdup.v1
vdup.b r1, v1
# CHECK-NEXT: vdup.h{{[ \t]+}}f1, v1
# long.vdup.v2
vdup.h f1, v1
# CHECK-NEXT: vdup.b{{[ \t]+}}1, v1
# long.vdup.v18.b
vdup.b 1, v1
# CHECK-NEXT: vdup.w{{[ \t]+}}1, v1
# long.vdup.v18.w
vdup.w 1, v1
# CHECK-NEXT: vdup.l{{[ \t]+}}1, v1
# long.vdup.v18.l
vdup.l 1, v1
# CHECK-NEXT: vdup.q{{[ \t]+}}1, v1
# long.vdup.v18.q
vdup.q 1, v1
# CHECK-NEXT: vextract.b{{[ \t]+}}v1, r1, r2
# extralong.vextract.v114
vextract.b v1, r1, r2
# CHECK-NEXT: vextract.h{{[ \t]+}}v1, r1, f1
# extralong.vextract.v116
vextract.h v1, r1, f1
# CHECK-NEXT: vextsl.b{{[ \t]+}}p0, v1, v2
# extralong.vextsl.v75
vextsl.b p0, v1, v2
# CHECK-NEXT: vextsq.b{{[ \t]+}}p0, v1, v2
# extralong.vextsq.v77
vextsq.b p0, v1, v2
# CHECK-NEXT: vextsw.b{{[ \t]+}}p0, v1, v2
# extralong.vextsw.v73
vextsw.b p0, v1, v2
# CHECK-NEXT: vextzl.b{{[ \t]+}}p0, v1, v2
# extralong.vextzl.v74
vextzl.b p0, v1, v2
# CHECK-NEXT: vextzq.b{{[ \t]+}}p0, v1, v2
# extralong.vextzq.v76
vextzq.b p0, v1, v2
# CHECK-NEXT: vextzw.b{{[ \t]+}}p0, v1, v2
# extralong.vextzw.v72
vextzw.b p0, v1, v2
# CHECK-NEXT: vfloor.h{{[ \t]+}}p0, v1
# long.vfloor.v41
vfloor.h p0, v1
# CHECK-NEXT: vfloor.h{{[ \t]+}}p0, [r3], v1
# xxlong.vfloor.v208
vfloor.h p0, [r3], v1
# CHECK-NEXT: vfloor.h{{[ \t]+}}p0, v1, [r3]
# xxlong.vfloor.v209
vfloor.h p0, v1, [r3]
# CHECK-NEXT: vgather1.b{{[ \t]+}}p0, [r1 + r2 * r3], v1
# xxlong.vgather1.v239
vgather1.b p0, [r1 + r2 * r3], v1
# CHECK-NEXT: vgather1.l{{[ \t]+}}p0, [v1[r1]], v2
# xxlong.vgather1.v240
vgather1.l p0, [v1[r1]], v2
# CHECK-NEXT: vgather1.q{{[ \t]+}}p0, [v1[r1]], v2
# xxlong.vgather1.v241
vgather1.q p0, [v1[r1]], v2
# CHECK-NEXT: vgather1.b{{[ \t]+}}p0, [r1 + v1[r2]], v2
# xxlong.vgather1.v242
vgather1.b p0, [r1 + v1[r2]], v2
# CHECK-NEXT: vgather1.b{{[ \t]+}}p0, [r1 + v1[r2] * 1], v2
# xxlong.vgather1.v243
vgather1.b p0, [r1 + v1[r2] * 1], v2
# CHECK-NEXT: vgather1.b{{[ \t]+}}p0, [r1 + v1[r2] * 1 + 1], v2
# xxlong.vgather1.v244
vgather1.b p0, [r1 + v1[r2] * 1 + 1], v2
# CHECK-NEXT: vgather1.b{{[ \t]+}}p0, [r1 + v1[r2] * 1 + 1], v2
# xxlong.vgather1.v245
vgather1.b p0, [r1 + v1[r2] * 1 + 1], v2
# CHECK-NEXT: vgather1.b{{[ \t]+}}p0, [r1 + v1[r2] * 1 + 1], v2
# xxlong.vgather1.v246
vgather1.b p0, [r1 + v1[r2] * 1 + 1], v2
# CHECK-NEXT: vgather1.b{{[ \t]+}}p0, [r1 + v1[r2] * 1 + 1], v2
# xxlong.vgather1.v247
vgather1.b p0, [r1 + v1[r2] * 1 + 1], v2
# CHECK-NEXT: vindex.b{{[ \t]+}}v1
# long.vindex.v17
vindex.b v1
# CHECK-NEXT: vinsert.b{{[ \t]+}}r1, r2, v1
# extralong.vinsert.v115
vinsert.b r1, r2, v1
# CHECK-NEXT: vinsert.h{{[ \t]+}}f1, r1, v1
# extralong.vinsert.v117
vinsert.h f1, r1, v1
# CHECK-NEXT: vlcadd.b{{[ \t]+}}1, r1
# long.vlcadd.v21
vlcadd.b 1, r1
# CHECK-NEXT: vlcnt.b{{[ \t]+}}r1
# long.vlcnt.v20
vlcnt.b r1
# CHECK-NEXT: vmadd.h{{[ \t]+}}p0, v1, v2, v3
# extralong.vmadd.v102
vmadd.h p0, v1, v2, v3
# CHECK-NEXT: vmax.h{{[ \t]+}}p0, v1, v2
# extralong.vmax.v69
vmax.h p0, v1, v2
# CHECK-NEXT: vmax.h{{[ \t]+}}p0, [r3], v1
# xxlong.vmax.v178
vmax.h p0, [r3], v1
# CHECK-NEXT: vmax.h{{[ \t]+}}p0, v1, [r3]
# xxlong.vmax.v179
vmax.h p0, v1, [r3]
# CHECK-NEXT: vmaxs.b{{[ \t]+}}p0, v1, v2
# extralong.vmaxs.v58
vmaxs.b p0, v1, v2
# CHECK-NEXT: vmaxs.b{{[ \t]+}}p0, [r3], v1
# xxlong.vmaxs.v156
vmaxs.b p0, [r3], v1
# CHECK-NEXT: vmaxs.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vmaxs.v157
vmaxs.b p0, v1, [r3]
# CHECK-NEXT: vmaxu.b{{[ \t]+}}p0, v1, v2
# extralong.vmaxu.v59
vmaxu.b p0, v1, v2
# CHECK-NEXT: vmaxu.b{{[ \t]+}}p0, [r3], v1
# xxlong.vmaxu.v158
vmaxu.b p0, [r3], v1
# CHECK-NEXT: vmaxu.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vmaxu.v159
vmaxu.b p0, v1, [r3]
# CHECK-NEXT: vmin.h{{[ \t]+}}p0, v1, v2
# extralong.vmin.v68
vmin.h p0, v1, v2
# CHECK-NEXT: vmin.h{{[ \t]+}}p0, [r3], v1
# xxlong.vmin.v176
vmin.h p0, [r3], v1
# CHECK-NEXT: vmin.h{{[ \t]+}}p0, v1, [r3]
# xxlong.vmin.v177
vmin.h p0, v1, [r3]
# CHECK-NEXT: vmins.b{{[ \t]+}}p0, v1, v2
# extralong.vmins.v56
vmins.b p0, v1, v2
# CHECK-NEXT: vmins.b{{[ \t]+}}p0, [r3], v1
# xxlong.vmins.v152
vmins.b p0, [r3], v1
# CHECK-NEXT: vmins.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vmins.v153
vmins.b p0, v1, [r3]
# CHECK-NEXT: vminu.b{{[ \t]+}}p0, v1, v2
# extralong.vminu.v57
vminu.b p0, v1, v2
# CHECK-NEXT: vminu.b{{[ \t]+}}p0, [r3], v1
# xxlong.vminu.v154
vminu.b p0, [r3], v1
# CHECK-NEXT: vminu.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vminu.v155
vminu.b p0, v1, [r3]
# CHECK-NEXT: vmov{{[ \t]+}}v1, v2
# long.vmov.v3
vmov v1, v2
# CHECK-NEXT: vmov.b{{[ \t]+}}p0, v1, v2
# extralong.vmov.v91
vmov.b p0, v1, v2
# CHECK-NEXT: vmov.b{{[ \t]+}}p0, [r3], v1
# xxlong.vmov.v137
vmov.b p0, [r3], v1
# CHECK-NEXT: vmov.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vmov.v138
vmov.b p0, v1, [r3]
# CHECK-NEXT: vmovz.b{{[ \t]+}}p0, [r3], v1
# xxlong.vmovz.v139
vmovz.b p0, [r3], v1
# CHECK-NEXT: vmsub.h{{[ \t]+}}p0, v1, v2, v3
# extralong.vmsub.v103
vmsub.h p0, v1, v2, v3
# CHECK-NEXT: vmul.b{{[ \t]+}}p0, v1, v2
# extralong.vmul.v52
vmul.b p0, v1, v2
# CHECK-NEXT: vmul.b{{[ \t]+}}p0, [r3], v1
# xxlong.vmul.v144
vmul.b p0, [r3], v1
# CHECK-NEXT: vmul.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vmul.v145
vmul.b p0, v1, [r3]
# CHECK-NEXT: vmulhs.b{{[ \t]+}}p0, v1, v2
# extralong.vmulhs.v60
vmulhs.b p0, v1, v2
# CHECK-NEXT: vmulhs.b{{[ \t]+}}p0, [r3], v1
# xxlong.vmulhs.v160
vmulhs.b p0, [r3], v1
# CHECK-NEXT: vmulhs.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vmulhs.v161
vmulhs.b p0, v1, [r3]
# CHECK-NEXT: vmulhsu.b{{[ \t]+}}p0, v1, v2
# extralong.vmulhsu.v62
vmulhsu.b p0, v1, v2
# CHECK-NEXT: vmulhsu.b{{[ \t]+}}p0, [r3], v1
# xxlong.vmulhsu.v164
vmulhsu.b p0, [r3], v1
# CHECK-NEXT: vmulhsu.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vmulhsu.v165
vmulhsu.b p0, v1, [r3]
# CHECK-NEXT: vmulhu.b{{[ \t]+}}p0, v1, v2
# extralong.vmulhu.v61
vmulhu.b p0, v1, v2
# CHECK-NEXT: vmulhu.b{{[ \t]+}}p0, [r3], v1
# xxlong.vmulhu.v162
vmulhu.b p0, [r3], v1
# CHECK-NEXT: vmulhu.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vmulhu.v163
vmulhu.b p0, v1, [r3]
# CHECK-NEXT: vneg.b{{[ \t]+}}p0, v1
# long.vneg.v29
vneg.b p0, v1
# CHECK-NEXT: vneg.b{{[ \t]+}}p0, [r3], v1
# xxlong.vneg.v184
vneg.b p0, [r3], v1
# CHECK-NEXT: vneg.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vneg.v185
vneg.b p0, v1, [r3]
# CHECK-NEXT: vnmadd.h{{[ \t]+}}p0, v1, v2, v3
# extralong.vnmadd.v104
vnmadd.h p0, v1, v2, v3
# CHECK-NEXT: vnmsub.h{{[ \t]+}}p0, v1, v2, v3
# extralong.vnmsub.v105
vnmsub.h p0, v1, v2, v3
# CHECK-NEXT: vnot.b{{[ \t]+}}p0, v1
# long.vnot.v31
vnot.b p0, v1
# CHECK-NEXT: vnot.b{{[ \t]+}}p0, [r3], v1
# xxlong.vnot.v188
vnot.b p0, [r3], v1
# CHECK-NEXT: vnot.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vnot.v189
vnot.b p0, v1, [r3]
# CHECK-NEXT: vor.b{{[ \t]+}}p0, v1, v2
# extralong.vor.v54
vor.b p0, v1, v2
# CHECK-NEXT: vor.b{{[ \t]+}}p0, [r3], v1
# xxlong.vor.v148
vor.b p0, [r3], v1
# CHECK-NEXT: vor.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vor.v149
vor.b p0, v1, [r3]
# CHECK-NEXT: vperm.b{{[ \t]+}}p0, v1, v2
# extralong.vperm.v92
vperm.b p0, v1, v2
# CHECK-NEXT: vpopcnt.b{{[ \t]+}}p0, v1
# long.vpopcnt.v36
vpopcnt.b p0, v1
# CHECK-NEXT: vpopcnt.b{{[ \t]+}}p0, [r3], v1
# xxlong.vpopcnt.v198
vpopcnt.b p0, [r3], v1
# CHECK-NEXT: vpopcnt.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vpopcnt.v199
vpopcnt.b p0, v1, [r3]
# CHECK-NEXT: vredadd.b{{[ \t]+}}p0, v1, r1
# extralong.vredadd.v118
vredadd.b p0, v1, r1
# CHECK-NEXT: vredadd.h{{[ \t]+}}p0, v1, f1
# extralong.vredadd.v126
vredadd.h p0, v1, f1
# CHECK-NEXT: vredadd.b{{[ \t]+}}p0, [r3], r1
# xxlong.vredadd.v219
vredadd.b p0, [r3], r1
# CHECK-NEXT: vredadd.h{{[ \t]+}}p0, [r3], f1
# xxlong.vredadd.v227
vredadd.h p0, [r3], f1
# CHECK-NEXT: vredand.b{{[ \t]+}}p0, v1, r1
# extralong.vredand.v123
vredand.b p0, v1, r1
# CHECK-NEXT: vredand.b{{[ \t]+}}p0, [r3], r1
# xxlong.vredand.v224
vredand.b p0, [r3], r1
# CHECK-NEXT: vredmax.h{{[ \t]+}}p0, v1, f1
# extralong.vredmax.v128
vredmax.h p0, v1, f1
# CHECK-NEXT: vredmax.h{{[ \t]+}}p0, [r3], f1
# xxlong.vredmax.v229
vredmax.h p0, [r3], f1
# CHECK-NEXT: vredmaxs.b{{[ \t]+}}p0, v1, r1
# extralong.vredmaxs.v121
vredmaxs.b p0, v1, r1
# CHECK-NEXT: vredmaxs.b{{[ \t]+}}p0, [r3], r1
# xxlong.vredmaxs.v222
vredmaxs.b p0, [r3], r1
# CHECK-NEXT: vredmaxu.b{{[ \t]+}}p0, v1, r1
# extralong.vredmaxu.v122
vredmaxu.b p0, v1, r1
# CHECK-NEXT: vredmaxu.b{{[ \t]+}}p0, [r3], r1
# xxlong.vredmaxu.v223
vredmaxu.b p0, [r3], r1
# CHECK-NEXT: vredmin.h{{[ \t]+}}p0, v1, f1
# extralong.vredmin.v127
vredmin.h p0, v1, f1
# CHECK-NEXT: vredmin.h{{[ \t]+}}p0, [r3], f1
# xxlong.vredmin.v228
vredmin.h p0, [r3], f1
# CHECK-NEXT: vredmins.b{{[ \t]+}}p0, v1, r1
# extralong.vredmins.v119
vredmins.b p0, v1, r1
# CHECK-NEXT: vredmins.b{{[ \t]+}}p0, [r3], r1
# xxlong.vredmins.v220
vredmins.b p0, [r3], r1
# CHECK-NEXT: vredminu.b{{[ \t]+}}p0, v1, r1
# extralong.vredminu.v120
vredminu.b p0, v1, r1
# CHECK-NEXT: vredminu.b{{[ \t]+}}p0, [r3], r1
# xxlong.vredminu.v221
vredminu.b p0, [r3], r1
# CHECK-NEXT: vredor.b{{[ \t]+}}p0, v1, r1
# extralong.vredor.v124
vredor.b p0, v1, r1
# CHECK-NEXT: vredor.b{{[ \t]+}}p0, [r3], r1
# xxlong.vredor.v225
vredor.b p0, [r3], r1
# CHECK-NEXT: vredxor.b{{[ \t]+}}p0, v1, r1
# extralong.vredxor.v125
vredxor.b p0, v1, r1
# CHECK-NEXT: vredxor.b{{[ \t]+}}p0, [r3], r1
# xxlong.vredxor.v226
vredxor.b p0, [r3], r1
# CHECK-NEXT: vrevbyte.w{{[ \t]+}}p0, v1
# long.vrevbyte.v37
vrevbyte.w p0, v1
# CHECK-NEXT: vrevbyte.w{{[ \t]+}}p0, [r3], v1
# xxlong.vrevbyte.v200
vrevbyte.w p0, [r3], v1
# CHECK-NEXT: vrevbyte.w{{[ \t]+}}p0, v1, [r3]
# xxlong.vrevbyte.v201
vrevbyte.w p0, v1, [r3]
# CHECK-NEXT: vrol.b{{[ \t]+}}p0, v1, v2
# extralong.vrol.v66
vrol.b p0, v1, v2
# CHECK-NEXT: vrol.b{{[ \t]+}}p0, 1, v1
# extralong.vrol.v110
vrol.b p0, 1, v1
# CHECK-NEXT: vrol.b{{[ \t]+}}p0, [r3], v1
# xxlong.vrol.v172
vrol.b p0, [r3], v1
# CHECK-NEXT: vrol.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vrol.v173
vrol.b p0, v1, [r3]
# CHECK-NEXT: vrol.b{{[ \t]+}}p0, 1, [r3]
# xxlong.vrol.v217
vrol.b p0, 1, [r3]
# CHECK-NEXT: vror.b{{[ \t]+}}p0, v1, v2
# extralong.vror.v67
vror.b p0, v1, v2
# CHECK-NEXT: vror.b{{[ \t]+}}p0, 1, v1
# extralong.vror.v111
vror.b p0, 1, v1
# CHECK-NEXT: vror.b{{[ \t]+}}p0, [r3], v1
# xxlong.vror.v174
vror.b p0, [r3], v1
# CHECK-NEXT: vror.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vror.v175
vror.b p0, v1, [r3]
# CHECK-NEXT: vror.b{{[ \t]+}}p0, 1, [r3]
# xxlong.vror.v218
vror.b p0, 1, [r3]
# CHECK-NEXT: vround.h{{[ \t]+}}p0, v1
# long.vround.v39
vround.h p0, v1
# CHECK-NEXT: vround.h{{[ \t]+}}p0, [r3], v1
# xxlong.vround.v204
vround.h p0, [r3], v1
# CHECK-NEXT: vround.h{{[ \t]+}}p0, v1, [r3]
# xxlong.vround.v205
vround.h p0, v1, [r3]
# CHECK-NEXT: vsar.b{{[ \t]+}}p0, v1, v2
# extralong.vsar.v65
vsar.b p0, v1, v2
# CHECK-NEXT: vsar.b{{[ \t]+}}p0, 1, v1
# extralong.vsar.v109
vsar.b p0, 1, v1
# CHECK-NEXT: vsar.b{{[ \t]+}}p0, [r3], v1
# xxlong.vsar.v170
vsar.b p0, [r3], v1
# CHECK-NEXT: vsar.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vsar.v171
vsar.b p0, v1, [r3]
# CHECK-NEXT: vsar.b{{[ \t]+}}p0, 1, [r3]
# xxlong.vsar.v216
vsar.b p0, 1, [r3]
# CHECK-NEXT: vscatter1.b{{[ \t]+}}p0, v1, [r1 + r2 * r3]
# xxlong.vscatter1.v248
vscatter1.b p0, v1, [r1 + r2 * r3]
# CHECK-NEXT: vscatter1.l{{[ \t]+}}p0, v1, [v2[r1]]
# xxlong.vscatter1.v249
vscatter1.l p0, v1, [v2[r1]]
# CHECK-NEXT: vscatter1.q{{[ \t]+}}p0, v1, [v2[r1]]
# xxlong.vscatter1.v250
vscatter1.q p0, v1, [v2[r1]]
# CHECK-NEXT: vscatter1.b{{[ \t]+}}p0, v1, [r1 + v2[r2]]
# xxlong.vscatter1.v251
vscatter1.b p0, v1, [r1 + v2[r2]]
# CHECK-NEXT: vscatter1.b{{[ \t]+}}p0, v1, [r1 + v2[r2] * 1]
# xxlong.vscatter1.v252
vscatter1.b p0, v1, [r1 + v2[r2] * 1]
# CHECK-NEXT: vscatter1.b{{[ \t]+}}p0, v1, [r1 + v2[r2] * 1 + 1]
# xxlong.vscatter1.v253
vscatter1.b p0, v1, [r1 + v2[r2] * 1 + 1]
# CHECK-NEXT: vscatter1.b{{[ \t]+}}p0, v1, [r1 + v2[r2] * 1 + 1]
# xxlong.vscatter1.v254
vscatter1.b p0, v1, [r1 + v2[r2] * 1 + 1]
# CHECK-NEXT: vscatter1.b{{[ \t]+}}p0, v1, [r1 + v2[r2] * 1 + 1]
# xxlong.vscatter1.v255
vscatter1.b p0, v1, [r1 + v2[r2] * 1 + 1]
# CHECK-NEXT: vscatter1.b{{[ \t]+}}p0, v1, [r1 + v2[r2] * 1 + 1]
# xxlong.vscatter1.v256
vscatter1.b p0, v1, [r1 + v2[r2] * 1 + 1]
# CHECK-NEXT: vshl.b{{[ \t]+}}p0, v1, v2
# extralong.vshl.v63
vshl.b p0, v1, v2
# CHECK-NEXT: vshl.b{{[ \t]+}}p0, 1, v1
# extralong.vshl.v107
vshl.b p0, 1, v1
# CHECK-NEXT: vshl.b{{[ \t]+}}p0, [r3], v1
# xxlong.vshl.v166
vshl.b p0, [r3], v1
# CHECK-NEXT: vshl.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vshl.v167
vshl.b p0, v1, [r3]
# CHECK-NEXT: vshl.b{{[ \t]+}}p0, 1, [r3]
# xxlong.vshl.v214
vshl.b p0, 1, [r3]
# CHECK-NEXT: vshr.b{{[ \t]+}}p0, v1, v2
# extralong.vshr.v64
vshr.b p0, v1, v2
# CHECK-NEXT: vshr.b{{[ \t]+}}p0, 1, v1
# extralong.vshr.v108
vshr.b p0, 1, v1
# CHECK-NEXT: vshr.b{{[ \t]+}}p0, [r3], v1
# xxlong.vshr.v168
vshr.b p0, [r3], v1
# CHECK-NEXT: vshr.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vshr.v169
vshr.b p0, v1, [r3]
# CHECK-NEXT: vshr.b{{[ \t]+}}p0, 1, [r3]
# xxlong.vshr.v215
vshr.b p0, 1, [r3]
# CHECK-NEXT: vslice.b{{[ \t]+}}p0, v1, 1, v2
# extralong.vslice.v106
vslice.b p0, v1, 1, v2
# CHECK-NEXT: vslidedn.b{{[ \t]+}}p0, 1, v1
# extralong.vslidedn.v113
vslidedn.b p0, 1, v1
# CHECK-NEXT: vslideup.b{{[ \t]+}}p0, 1, v1
# extralong.vslideup.v112
vslideup.b p0, 1, v1
# CHECK-NEXT: vsqrt.h{{[ \t]+}}p0, v1
# long.vsqrt.v38
vsqrt.h p0, v1
# CHECK-NEXT: vsqrt.h{{[ \t]+}}p0, [r3], v1
# xxlong.vsqrt.v202
vsqrt.h p0, [r3], v1
# CHECK-NEXT: vsqrt.h{{[ \t]+}}p0, v1, [r3]
# xxlong.vsqrt.v203
vsqrt.h p0, v1, [r3]
# CHECK-NEXT: vsub.b{{[ \t]+}}p0, v1, v2
# extralong.vsub.v51
vsub.b p0, v1, v2
# CHECK-NEXT: vsub.b{{[ \t]+}}p0, [r3], v1
# xxlong.vsub.v142
vsub.b p0, [r3], v1
# CHECK-NEXT: vsub.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vsub.v143
vsub.b p0, v1, [r3]
# CHECK-NEXT: vtestnz.b{{[ \t]+}}p0, v1, v2, p1
# extralong.vtestnz.v49
vtestnz.b p0, v1, v2, p1
# CHECK-NEXT: vtestnz.b{{[ \t]+}}p0, v1, [r3], p1
# xxlong.vtestnz.v232
vtestnz.b p0, v1, [r3], p1
# CHECK-NEXT: vtestz.b{{[ \t]+}}p0, v1, v2, p1
# extralong.vtestz.v48
vtestz.b p0, v1, v2, p1
# CHECK-NEXT: vtestz.b{{[ \t]+}}p0, v1, [r3], p1
# xxlong.vtestz.v231
vtestz.b p0, v1, [r3], p1
# CHECK-NEXT: vtrnhi.b{{[ \t]+}}p0, v1, v2
# extralong.vtrnhi.v98
vtrnhi.b p0, v1, v2
# CHECK-NEXT: vtrnlo.b{{[ \t]+}}p0, v1, v2
# extralong.vtrnlo.v97
vtrnlo.b p0, v1, v2
# CHECK-NEXT: vtrunc.h{{[ \t]+}}p0, v1
# long.vtrunc.v40
vtrunc.h p0, v1
# CHECK-NEXT: vtrunc.h{{[ \t]+}}p0, [r3], v1
# xxlong.vtrunc.v206
vtrunc.h p0, [r3], v1
# CHECK-NEXT: vtrunc.h{{[ \t]+}}p0, v1, [r3]
# xxlong.vtrunc.v207
vtrunc.h p0, v1, [r3]
# CHECK-NEXT: vtruncb.w{{[ \t]+}}p0, v1, v2
# extralong.vtruncb.v78
vtruncb.w p0, v1, v2
# CHECK-NEXT: vtruncl.q{{[ \t]+}}p0, v1, v2
# extralong.vtruncl.v80
vtruncl.q p0, v1, v2
# CHECK-NEXT: vtruncw.l{{[ \t]+}}p0, v1, v2
# extralong.vtruncw.v79
vtruncw.l p0, v1, v2
# CHECK-NEXT: vuziphi.b{{[ \t]+}}p0, v1, v2
# extralong.vuziphi.v96
vuziphi.b p0, v1, v2
# CHECK-NEXT: vuziplo.b{{[ \t]+}}p0, v1, v2
# extralong.vuziplo.v95
vuziplo.b p0, v1, v2
# CHECK-NEXT: vxor.b{{[ \t]+}}p0, v1, v2
# extralong.vxor.v55
vxor.b p0, v1, v2
# CHECK-NEXT: vxor.b{{[ \t]+}}p0, [r3], v1
# xxlong.vxor.v150
vxor.b p0, [r3], v1
# CHECK-NEXT: vxor.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vxor.v151
vxor.b p0, v1, [r3]
# CHECK-NEXT: vziphi.b{{[ \t]+}}p0, v1, v2
# extralong.vziphi.v94
vziphi.b p0, v1, v2
# CHECK-NEXT: vziplo.b{{[ \t]+}}p0, v1, v2
# extralong.vziplo.v93
vziplo.b p0, v1, v2
# CHECK-NEXT: pcount.w{{[ \t]+}}p0, r1
# long.pcount.v8 public width alias .h
pcount.h p0, r1
# CHECK-NEXT: pcount.l{{[ \t]+}}p0, r1
# long.pcount.v8 public width alias .s
pcount.s p0, r1
# CHECK-NEXT: pcount.q{{[ \t]+}}p0, r1
# long.pcount.v8 public width alias .d
pcount.d p0, r1
