# NOTE: Generated by spec/isa/tools/gen_llvm_vector_catalog.py.
# RUN: llvm-mc -triple=bedrock -mattr=+vectorfp -filetype=obj %s -o %t
# RUN: llvm-objdump -d --no-show-raw-insn %t | FileCheck %s

# CHECK: bpall.b{{[ \t]+}}p0, 1
# long.bpall.v28
bpall.b p0, 1
# CHECK-NEXT: bpall.b{{[ \t]+}}p0, [r3]
# xxlong.bpall.v238
bpall.b p0, [r3]
# CHECK-NEXT: bpany{{[ \t]+}}p0, 1
# long.bpany.v26
bpany p0, 1
# CHECK-NEXT: bpany{{[ \t]+}}p0, [r3]
# xxlong.bpany.v236
bpany p0, [r3]
# CHECK-NEXT: bpnone{{[ \t]+}}p0, 1
# long.bpnone.v27
bpnone p0, 1
# CHECK-NEXT: bpnone{{[ \t]+}}p0, [r3]
# xxlong.bpnone.v237
bpnone p0, [r3]
# CHECK-NEXT: pand{{[ \t]+}}p0, p1
# long.pand.v9
pand p0, p1
# CHECK-NEXT: pcount.b{{[ \t]+}}p0, r1
# long.pcount.v8
pcount.b p0, r1
# CHECK-NEXT: pfalse{{[ \t]+}}p0
# long.pfalse.v24
pfalse p0
# CHECK-NEXT: pfirst.b{{[ \t]+}}p0, r1
# long.pfirst.v6
pfirst.b p0, r1
# CHECK-NEXT: phead.b{{[ \t]+}}r1, p0
# long.phead.v4
phead.b r1, p0
# CHECK-NEXT: plast.b{{[ \t]+}}p0, r1
# long.plast.v7
plast.b p0, r1
# CHECK-NEXT: ploop.b{{[ \t]+}}r1, r2, p0, [r3]
# xxlong.ploop.v233
ploop.b r1, r2, p0, [r3]
# CHECK-NEXT: pmov{{[ \t]+}}[r3], p0
# xxlong.pmov.v234
pmov [r3], p0
# CHECK-NEXT: pmov{{[ \t]+}}p0, [r3]
# xxlong.pmov.v235
pmov p0, [r3]
# CHECK-NEXT: pnot{{[ \t]+}}p0
# long.pnot.v25
pnot p0
# CHECK-NEXT: por{{[ \t]+}}p0, p1
# long.por.v10
por p0, p1
# CHECK-NEXT: ppackhi.w{{[ \t]+}}p0, p1
# long.ppackhi.v15
ppackhi.w p0, p1
# CHECK-NEXT: ppacklo.w{{[ \t]+}}p0, p1
# long.ppacklo.v14
ppacklo.w p0, p1
# CHECK-NEXT: pperm.b{{[ \t]+}}v1, p0
# long.pperm.v44
pperm.b v1, p0
# CHECK-NEXT: psel{{[ \t]+}}p0, p1, p2
# extralong.psel.v129
psel p0, p1, p2
# CHECK-NEXT: pslice.b{{[ \t]+}}p0, 1, p1
# extralong.pslice.v136
pslice.b p0, 1, p1
# CHECK-NEXT: pslidedn.b{{[ \t]+}}1, p0
# long.pslidedn.v46
pslidedn.b 1, p0
# CHECK-NEXT: pslideup.b{{[ \t]+}}1, p0
# long.pslideup.v45
pslideup.b 1, p0
# CHECK-NEXT: ptail.b{{[ \t]+}}r1, p0
# long.ptail.v5
ptail.b r1, p0
# CHECK-NEXT: ptrnhi.b{{[ \t]+}}p0, p1, p2
# extralong.ptrnhi.v135
ptrnhi.b p0, p1, p2
# CHECK-NEXT: ptrnlo.b{{[ \t]+}}p0, p1, p2
# extralong.ptrnlo.v134
ptrnlo.b p0, p1, p2
# CHECK-NEXT: ptrue.b{{[ \t]+}}p0
# long.ptrue.v23
ptrue.b p0
# CHECK-NEXT: punpkhi.b{{[ \t]+}}p0, p1
# long.punpkhi.v13
punpkhi.b p0, p1
# CHECK-NEXT: punpklo.b{{[ \t]+}}p0, p1
# long.punpklo.v12
punpklo.b p0, p1
# CHECK-NEXT: puziphi.b{{[ \t]+}}p0, p1, p2
# extralong.puziphi.v133
puziphi.b p0, p1, p2
# CHECK-NEXT: puziplo.b{{[ \t]+}}p0, p1, p2
# extralong.puziplo.v132
puziplo.b p0, p1, p2
# CHECK-NEXT: pxor{{[ \t]+}}p0, p1
# long.pxor.v11
pxor p0, p1
# CHECK-NEXT: pziphi.b{{[ \t]+}}p0, p1, p2
# extralong.pziphi.v131
pziphi.b p0, p1, p2
# CHECK-NEXT: pziplo.b{{[ \t]+}}p0, p1, p2
# extralong.pziplo.v130
pziplo.b p0, p1, p2
# CHECK-NEXT: vabs.b{{[ \t]+}}p0, v1
# long.vabs.v30
vabs.b p0, v1
# CHECK-NEXT: vabs.b{{[ \t]+}}p0, [r3], v1
# xxlong.vabs.v186
vabs.b p0, [r3], v1
# CHECK-NEXT: vabs.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vabs.v187
vabs.b p0, v1, [r3]
# CHECK-NEXT: vfabs.h{{[ \t]+}}p0, v1
vfabs.h p0, v1
# CHECK-NEXT: vfabs.h{{[ \t]+}}p0, [r3], v1
vfabs.h p0, [r3], v1
# CHECK-NEXT: vfabs.h{{[ \t]+}}p0, v1, [r3]
vfabs.h p0, v1, [r3]
# CHECK-NEXT: vadd.b{{[ \t]+}}p0, v1, v2
# extralong.vadd.v50
vadd.b p0, v1, v2
# CHECK-NEXT: vadd.b{{[ \t]+}}p0, [r3], v1
# xxlong.vadd.v140
vadd.b p0, [r3], v1
# CHECK-NEXT: vadd.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vadd.v141
vadd.b p0, v1, [r3]
# CHECK-NEXT: vfadd.h{{[ \t]+}}p0, v1, v2
vfadd.h p0, v1, v2
# CHECK-NEXT: vfadd.h{{[ \t]+}}p0, [r3], v1
vfadd.h p0, [r3], v1
# CHECK-NEXT: vfadd.h{{[ \t]+}}p0, v1, [r3]
vfadd.h p0, v1, [r3]
# CHECK-NEXT: vand.b{{[ \t]+}}p0, v1, v2
# extralong.vand.v53
vand.b p0, v1, v2
# CHECK-NEXT: vand.b{{[ \t]+}}p0, [r3], v1
# xxlong.vand.v146
vand.b p0, [r3], v1
# CHECK-NEXT: vand.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vand.v147
vand.b p0, v1, [r3]
# CHECK-NEXT: vfceil.h{{[ \t]+}}p0, v1
# long.vfceil.v42
vfceil.h p0, v1
# CHECK-NEXT: vfceil.h{{[ \t]+}}p0, [r3], v1
# xxlong.vfceil.v210
vfceil.h p0, [r3], v1
# CHECK-NEXT: vfceil.h{{[ \t]+}}p0, v1, [r3]
# xxlong.vfceil.v211
vfceil.h p0, v1, [r3]
# CHECK-NEXT: vfclass.h{{[ \t]+}}p0, v1
# long.vfclass.v43
vfclass.h p0, v1
# CHECK-NEXT: vfclass.h{{[ \t]+}}p0, [r3], v1
# xxlong.vfclass.v212
vfclass.h p0, [r3], v1
# CHECK-NEXT: vfclass.h{{[ \t]+}}p0, v1, [r3]
# xxlong.vfclass.v213
vfclass.h p0, v1, [r3]
# CHECK-NEXT: vclr{{[ \t]+}}v1
# long.vclr.v16
vclr v1
# CHECK-NEXT: vcls.b{{[ \t]+}}p0, v1
# long.vcls.v34
vcls.b p0, v1
# CHECK-NEXT: vcls.b{{[ \t]+}}p0, [r3], v1
# xxlong.vcls.v194
vcls.b p0, [r3], v1
# CHECK-NEXT: vcls.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vcls.v195
vcls.b p0, v1, [r3]
# CHECK-NEXT: vclz.b{{[ \t]+}}p0, v1
# long.vclz.v32
vclz.b p0, v1
# CHECK-NEXT: vclz.b{{[ \t]+}}p0, [r3], v1
# xxlong.vclz.v190
vclz.b p0, [r3], v1
# CHECK-NEXT: vclz.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vclz.v191
vclz.b p0, v1, [r3]
# CHECK-NEXT: vcmpeq.b{{[ \t]+}}p0, v1, v2, p1
# extralong.vcmpcc.v47.integer
vcmpeq.b p0, v1, v2, p1
# CHECK-NEXT: vfcmpeq.h{{[ \t]+}}p0, v1, v2, p1
# extralong.vfcmpcc.v47.fp
vfcmpeq.h p0, v1, v2, p1
# CHECK-NEXT: vcmpeq.b{{[ \t]+}}p0, v1, [r3], p1
# xxlong.vcmpcc.v230.integer
vcmpeq.b p0, v1, [r3], p1
# CHECK-NEXT: vfcmpeq.h{{[ \t]+}}p0, v1, [r3], p1
# xxlong.vfcmpcc.v230.fp
vfcmpeq.h p0, v1, [r3], p1
# CHECK-NEXT: vfcopysign.h{{[ \t]+}}p0, v1, v2
# extralong.vfcopysign.v71
vfcopysign.h p0, v1, v2
# CHECK-NEXT: vfcopysign.h{{[ \t]+}}p0, [r3], v1
# xxlong.vfcopysign.v182
vfcopysign.h p0, [r3], v1
# CHECK-NEXT: vfcopysign.h{{[ \t]+}}p0, v1, [r3]
# xxlong.vfcopysign.v183
vfcopysign.h p0, v1, [r3]
# CHECK-NEXT: vcts.b{{[ \t]+}}p0, v1
# long.vcts.v35
vcts.b p0, v1
# CHECK-NEXT: vcts.b{{[ \t]+}}p0, [r3], v1
# xxlong.vcts.v196
vcts.b p0, [r3], v1
# CHECK-NEXT: vcts.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vcts.v197
vcts.b p0, v1, [r3]
# CHECK-NEXT: vctz.b{{[ \t]+}}p0, v1
# long.vctz.v33
vctz.b p0, v1
# CHECK-NEXT: vctz.b{{[ \t]+}}p0, [r3], v1
# xxlong.vctz.v192
vctz.b p0, [r3], v1
# CHECK-NEXT: vctz.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vctz.v193
vctz.b p0, v1, [r3]
# CHECK-NEXT: vfcvtd.h{{[ \t]+}}p0, v1, v2
# extralong.vfcvtd.v82
vfcvtd.h p0, v1, v2
# CHECK-NEXT: vfcvtd.l{{[ \t]+}}p0, v1, v2
# extralong.vfcvtd.v85
vfcvtd.l p0, v1, v2
# CHECK-NEXT: vfcvth.s{{[ \t]+}}p0, v1, v2
# extralong.vfcvth.v99
vfcvth.s p0, v1, v2
# CHECK-NEXT: vfcvth.l{{[ \t]+}}p0, v1, v2
# extralong.vfcvth.v100
vfcvth.l p0, v1, v2
# CHECK-NEXT: vfcvtl.h{{[ \t]+}}p0, v1, v2
# extralong.vfcvtl.v87
vfcvtl.h p0, v1, v2
# CHECK-NEXT: vfcvtq.h{{[ \t]+}}p0, v1, v2
# extralong.vfcvtq.v89
vfcvtq.h p0, v1, v2
# CHECK-NEXT: vfcvts.h{{[ \t]+}}p0, v1, v2
# extralong.vfcvts.v81
vfcvts.h p0, v1, v2
# CHECK-NEXT: vfcvts.l{{[ \t]+}}p0, v1, v2
# extralong.vfcvts.v83
vfcvts.l p0, v1, v2
# CHECK-NEXT: vfcvtud.l{{[ \t]+}}p0, v1, v2
# extralong.vfcvtud.v86
vfcvtud.l p0, v1, v2
# CHECK-NEXT: vfcvtuh.l{{[ \t]+}}p0, v1, v2
# extralong.vfcvtuh.v101
vfcvtuh.l p0, v1, v2
# CHECK-NEXT: vfcvtul.h{{[ \t]+}}p0, v1, v2
# extralong.vfcvtul.v88
vfcvtul.h p0, v1, v2
# CHECK-NEXT: vfcvtuq.h{{[ \t]+}}p0, v1, v2
# extralong.vfcvtuq.v90
vfcvtuq.h p0, v1, v2
# CHECK-NEXT: vfcvtus.l{{[ \t]+}}p0, v1, v2
# extralong.vfcvtus.v84
vfcvtus.l p0, v1, v2
# CHECK-NEXT: vfdiv.h{{[ \t]+}}p0, v1, v2
# extralong.vfdiv.v70
vfdiv.h p0, v1, v2
# CHECK-NEXT: vfdiv.h{{[ \t]+}}p0, [r3], v1
# xxlong.vfdiv.v180
vfdiv.h p0, [r3], v1
# CHECK-NEXT: vfdiv.h{{[ \t]+}}p0, v1, [r3]
# xxlong.vfdiv.v181
vfdiv.h p0, v1, [r3]
# CHECK-NEXT: vdup.b{{[ \t]+}}r1, v1
# long.vdup.v1
vdup.b r1, v1
# CHECK-NEXT: vfdup.h{{[ \t]+}}f1, v1
# long.vfdup.v2
vfdup.h f1, v1
# CHECK-NEXT: vdup.b{{[ \t]+}}1, v1
# long.vdup.v18.b
vdup.b 1, v1
# CHECK-NEXT: vdup.w{{[ \t]+}}1, v1
# long.vdup.v18.w
vdup.w 1, v1
# CHECK-NEXT: vdup.l{{[ \t]+}}1, v1
# long.vdup.v18.l
vdup.l 1, v1
# CHECK-NEXT: vdup.q{{[ \t]+}}1, v1
# long.vdup.v18.q
vdup.q 1, v1
# CHECK-NEXT: vextract.b{{[ \t]+}}v1, r1, r2
# extralong.vextract.v114
vextract.b v1, r1, r2
# CHECK-NEXT: vfextract.h{{[ \t]+}}v1, r1, f1
# extralong.vfextract.v116
vfextract.h v1, r1, f1
# CHECK-NEXT: vextsl.b{{[ \t]+}}p0, v1, v2
# extralong.vextsl.v75
vextsl.b p0, v1, v2
# CHECK-NEXT: vextsq.b{{[ \t]+}}p0, v1, v2
# extralong.vextsq.v77
vextsq.b p0, v1, v2
# CHECK-NEXT: vextsw.b{{[ \t]+}}p0, v1, v2
# extralong.vextsw.v73
vextsw.b p0, v1, v2
# CHECK-NEXT: vextzl.b{{[ \t]+}}p0, v1, v2
# extralong.vextzl.v74
vextzl.b p0, v1, v2
# CHECK-NEXT: vextzq.b{{[ \t]+}}p0, v1, v2
# extralong.vextzq.v76
vextzq.b p0, v1, v2
# CHECK-NEXT: vextzw.b{{[ \t]+}}p0, v1, v2
# extralong.vextzw.v72
vextzw.b p0, v1, v2
# CHECK-NEXT: vffloor.h{{[ \t]+}}p0, v1
# long.vffloor.v41
vffloor.h p0, v1
# CHECK-NEXT: vffloor.h{{[ \t]+}}p0, [r3], v1
# xxlong.vffloor.v208
vffloor.h p0, [r3], v1
# CHECK-NEXT: vffloor.h{{[ \t]+}}p0, v1, [r3]
# xxlong.vffloor.v209
vffloor.h p0, v1, [r3]
# CHECK-NEXT: vgather.b{{[ \t]+}}p0, p1, [r1 + r2], v1
# xxlong.vgather.v239
vgather.b p0, p1, [r1 + r2], v1
# CHECK-NEXT: vgather.l{{[ \t]+}}p0, p1, [v1], v2
# xxlong.vgather.v240
vgather.l p0, p1, [v1], v2
# CHECK-NEXT: vgather.q{{[ \t]+}}p0, p1, [v1], v2
# xxlong.vgather.v241
vgather.q p0, p1, [v1], v2
# CHECK-NEXT: vgather.b{{[ \t]+}}p0, p1, [r1 + v1], v2
# xxlong.vgather.v242
vgather.b p0, p1, [r1 + v1], v2
# CHECK-NEXT: vgather.b{{[ \t]+}}p0, p1, [r1 + v1 * 1], v2
# xxlong.vgather.v243
vgather.b p0, p1, [r1 + v1 * 1], v2
# CHECK-NEXT: vgather.b{{[ \t]+}}p0, p1, [r1 + v1 * 1 + 1], v2
# xxlong.vgather.v244
vgather.b p0, p1, [r1 + v1 * 1 + 1], v2
# CHECK-NEXT: vgather.b{{[ \t]+}}p0, p1, [r1 + v1 * 1 + 1], v2
# xxlong.vgather.v245
vgather.b p0, p1, [r1 + v1 * 1 + 1], v2
# CHECK-NEXT: vgather.b{{[ \t]+}}p0, p1, [r1 + v1 * 1 + 1], v2
# xxlong.vgather.v246
vgather.b p0, p1, [r1 + v1 * 1 + 1], v2
# CHECK-NEXT: vgather.b{{[ \t]+}}p0, p1, [r1 + v1 * 1 + 1], v2
# xxlong.vgather.v247
vgather.b p0, p1, [r1 + v1 * 1 + 1], v2
# CHECK-NEXT: vindex.b{{[ \t]+}}v1
# long.vindex.v17
vindex.b v1
# CHECK-NEXT: vinsert.b{{[ \t]+}}r1, r2, v1
# extralong.vinsert.v115
vinsert.b r1, r2, v1
# CHECK-NEXT: vfinsert.h{{[ \t]+}}f1, r1, v1
# extralong.vfinsert.v117
vfinsert.h f1, r1, v1
# CHECK-NEXT: vlcadd.b{{[ \t]+}}1, r1
# long.vlcadd.v21
vlcadd.b 1, r1
# CHECK-NEXT: vlcnt.b{{[ \t]+}}r1
# long.vlcnt.v20
vlcnt.b r1
# CHECK-NEXT: vfmadd.h{{[ \t]+}}p0, v1, v2, v3
# extralong.vfmadd.v102
vfmadd.h p0, v1, v2, v3
# CHECK-NEXT: vfmax.h{{[ \t]+}}p0, v1, v2
# extralong.vfmax.v69
vfmax.h p0, v1, v2
# CHECK-NEXT: vfmax.h{{[ \t]+}}p0, [r3], v1
# xxlong.vfmax.v178
vfmax.h p0, [r3], v1
# CHECK-NEXT: vfmax.h{{[ \t]+}}p0, v1, [r3]
# xxlong.vfmax.v179
vfmax.h p0, v1, [r3]
# CHECK-NEXT: vmaxs.b{{[ \t]+}}p0, v1, v2
# extralong.vmaxs.v58
vmaxs.b p0, v1, v2
# CHECK-NEXT: vmaxs.b{{[ \t]+}}p0, [r3], v1
# xxlong.vmaxs.v156
vmaxs.b p0, [r3], v1
# CHECK-NEXT: vmaxs.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vmaxs.v157
vmaxs.b p0, v1, [r3]
# CHECK-NEXT: vmaxu.b{{[ \t]+}}p0, v1, v2
# extralong.vmaxu.v59
vmaxu.b p0, v1, v2
# CHECK-NEXT: vmaxu.b{{[ \t]+}}p0, [r3], v1
# xxlong.vmaxu.v158
vmaxu.b p0, [r3], v1
# CHECK-NEXT: vmaxu.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vmaxu.v159
vmaxu.b p0, v1, [r3]
# CHECK-NEXT: vfmin.h{{[ \t]+}}p0, v1, v2
# extralong.vfmin.v68
vfmin.h p0, v1, v2
# CHECK-NEXT: vfmin.h{{[ \t]+}}p0, [r3], v1
# xxlong.vfmin.v176
vfmin.h p0, [r3], v1
# CHECK-NEXT: vfmin.h{{[ \t]+}}p0, v1, [r3]
# xxlong.vfmin.v177
vfmin.h p0, v1, [r3]
# CHECK-NEXT: vmins.b{{[ \t]+}}p0, v1, v2
# extralong.vmins.v56
vmins.b p0, v1, v2
# CHECK-NEXT: vmins.b{{[ \t]+}}p0, [r3], v1
# xxlong.vmins.v152
vmins.b p0, [r3], v1
# CHECK-NEXT: vmins.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vmins.v153
vmins.b p0, v1, [r3]
# CHECK-NEXT: vminu.b{{[ \t]+}}p0, v1, v2
# extralong.vminu.v57
vminu.b p0, v1, v2
# CHECK-NEXT: vminu.b{{[ \t]+}}p0, [r3], v1
# xxlong.vminu.v154
vminu.b p0, [r3], v1
# CHECK-NEXT: vminu.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vminu.v155
vminu.b p0, v1, [r3]
# CHECK-NEXT: vmov{{[ \t]+}}v1, v2
# long.vmov.v3
vmov v1, v2
# CHECK-NEXT: vmov.b{{[ \t]+}}p0, v1, v2
# extralong.vmov.v91
vmov.b p0, v1, v2
# CHECK-NEXT: vmov.b{{[ \t]+}}p0, [r3], v1
# xxlong.vmov.v137
vmov.b p0, [r3], v1
# CHECK-NEXT: vmov.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vmov.v138
vmov.b p0, v1, [r3]
# CHECK-NEXT: vmovz.b{{[ \t]+}}p0, [r3], v1
# xxlong.vmovz.v139
vmovz.b p0, [r3], v1
# CHECK-NEXT: vfmsub.h{{[ \t]+}}p0, v1, v2, v3
# extralong.vfmsub.v103
vfmsub.h p0, v1, v2, v3
# CHECK-NEXT: vmul.b{{[ \t]+}}p0, v1, v2
# extralong.vmul.v52
vmul.b p0, v1, v2
# CHECK-NEXT: vmul.b{{[ \t]+}}p0, [r3], v1
# xxlong.vmul.v144
vmul.b p0, [r3], v1
# CHECK-NEXT: vmul.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vmul.v145
vmul.b p0, v1, [r3]
# CHECK-NEXT: vfmul.h{{[ \t]+}}p0, v1, v2
vfmul.h p0, v1, v2
# CHECK-NEXT: vfmul.h{{[ \t]+}}p0, [r3], v1
vfmul.h p0, [r3], v1
# CHECK-NEXT: vfmul.h{{[ \t]+}}p0, v1, [r3]
vfmul.h p0, v1, [r3]
# CHECK-NEXT: vmulhs.b{{[ \t]+}}p0, v1, v2
# extralong.vmulhs.v60
vmulhs.b p0, v1, v2
# CHECK-NEXT: vmulhs.b{{[ \t]+}}p0, [r3], v1
# xxlong.vmulhs.v160
vmulhs.b p0, [r3], v1
# CHECK-NEXT: vmulhs.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vmulhs.v161
vmulhs.b p0, v1, [r3]
# CHECK-NEXT: vmulhsu.b{{[ \t]+}}p0, v1, v2
# extralong.vmulhsu.v62
vmulhsu.b p0, v1, v2
# CHECK-NEXT: vmulhsu.b{{[ \t]+}}p0, [r3], v1
# xxlong.vmulhsu.v164
vmulhsu.b p0, [r3], v1
# CHECK-NEXT: vmulhsu.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vmulhsu.v165
vmulhsu.b p0, v1, [r3]
# CHECK-NEXT: vmulhu.b{{[ \t]+}}p0, v1, v2
# extralong.vmulhu.v61
vmulhu.b p0, v1, v2
# CHECK-NEXT: vmulhu.b{{[ \t]+}}p0, [r3], v1
# xxlong.vmulhu.v162
vmulhu.b p0, [r3], v1
# CHECK-NEXT: vmulhu.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vmulhu.v163
vmulhu.b p0, v1, [r3]
# CHECK-NEXT: vneg.b{{[ \t]+}}p0, v1
# long.vneg.v29
vneg.b p0, v1
# CHECK-NEXT: vneg.b{{[ \t]+}}p0, [r3], v1
# xxlong.vneg.v184
vneg.b p0, [r3], v1
# CHECK-NEXT: vneg.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vneg.v185
vneg.b p0, v1, [r3]
# CHECK-NEXT: vfneg.h{{[ \t]+}}p0, v1
vfneg.h p0, v1
# CHECK-NEXT: vfneg.h{{[ \t]+}}p0, [r3], v1
vfneg.h p0, [r3], v1
# CHECK-NEXT: vfneg.h{{[ \t]+}}p0, v1, [r3]
vfneg.h p0, v1, [r3]
# CHECK-NEXT: vfnmadd.h{{[ \t]+}}p0, v1, v2, v3
# extralong.vfnmadd.v104
vfnmadd.h p0, v1, v2, v3
# CHECK-NEXT: vfnmsub.h{{[ \t]+}}p0, v1, v2, v3
# extralong.vfnmsub.v105
vfnmsub.h p0, v1, v2, v3
# CHECK-NEXT: vnot.b{{[ \t]+}}p0, v1
# long.vnot.v31
vnot.b p0, v1
# CHECK-NEXT: vnot.b{{[ \t]+}}p0, [r3], v1
# xxlong.vnot.v188
vnot.b p0, [r3], v1
# CHECK-NEXT: vnot.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vnot.v189
vnot.b p0, v1, [r3]
# CHECK-NEXT: vor.b{{[ \t]+}}p0, v1, v2
# extralong.vor.v54
vor.b p0, v1, v2
# CHECK-NEXT: vor.b{{[ \t]+}}p0, [r3], v1
# xxlong.vor.v148
vor.b p0, [r3], v1
# CHECK-NEXT: vor.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vor.v149
vor.b p0, v1, [r3]
# CHECK-NEXT: vperm.b{{[ \t]+}}p0, v1, v2
# extralong.vperm.v92
vperm.b p0, v1, v2
# CHECK-NEXT: vpopcnt.b{{[ \t]+}}p0, v1
# long.vpopcnt.v36
vpopcnt.b p0, v1
# CHECK-NEXT: vpopcnt.b{{[ \t]+}}p0, [r3], v1
# xxlong.vpopcnt.v198
vpopcnt.b p0, [r3], v1
# CHECK-NEXT: vpopcnt.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vpopcnt.v199
vpopcnt.b p0, v1, [r3]
# CHECK-NEXT: vredadd.b{{[ \t]+}}p0, v1, r1
# extralong.vredadd.v118
vredadd.b p0, v1, r1
# CHECK-NEXT: vfredadd.h{{[ \t]+}}p0, v1, f1
# extralong.vfredadd.v126
vfredadd.h p0, v1, f1
# CHECK-NEXT: vredadd.b{{[ \t]+}}p0, [r3], r1
# xxlong.vredadd.v219
vredadd.b p0, [r3], r1
# CHECK-NEXT: vfredadd.h{{[ \t]+}}p0, [r3], f1
# xxlong.vfredadd.v227
vfredadd.h p0, [r3], f1
# CHECK-NEXT: vredand.b{{[ \t]+}}p0, v1, r1
# extralong.vredand.v123
vredand.b p0, v1, r1
# CHECK-NEXT: vredand.b{{[ \t]+}}p0, [r3], r1
# xxlong.vredand.v224
vredand.b p0, [r3], r1
# CHECK-NEXT: vfredmax.h{{[ \t]+}}p0, v1, f1
# extralong.vfredmax.v128
vfredmax.h p0, v1, f1
# CHECK-NEXT: vfredmax.h{{[ \t]+}}p0, [r3], f1
# xxlong.vfredmax.v229
vfredmax.h p0, [r3], f1
# CHECK-NEXT: vredmaxs.b{{[ \t]+}}p0, v1, r1
# extralong.vredmaxs.v121
vredmaxs.b p0, v1, r1
# CHECK-NEXT: vredmaxs.b{{[ \t]+}}p0, [r3], r1
# xxlong.vredmaxs.v222
vredmaxs.b p0, [r3], r1
# CHECK-NEXT: vredmaxu.b{{[ \t]+}}p0, v1, r1
# extralong.vredmaxu.v122
vredmaxu.b p0, v1, r1
# CHECK-NEXT: vredmaxu.b{{[ \t]+}}p0, [r3], r1
# xxlong.vredmaxu.v223
vredmaxu.b p0, [r3], r1
# CHECK-NEXT: vfredmin.h{{[ \t]+}}p0, v1, f1
# extralong.vfredmin.v127
vfredmin.h p0, v1, f1
# CHECK-NEXT: vfredmin.h{{[ \t]+}}p0, [r3], f1
# xxlong.vfredmin.v228
vfredmin.h p0, [r3], f1
# CHECK-NEXT: vredmins.b{{[ \t]+}}p0, v1, r1
# extralong.vredmins.v119
vredmins.b p0, v1, r1
# CHECK-NEXT: vredmins.b{{[ \t]+}}p0, [r3], r1
# xxlong.vredmins.v220
vredmins.b p0, [r3], r1
# CHECK-NEXT: vredminu.b{{[ \t]+}}p0, v1, r1
# extralong.vredminu.v120
vredminu.b p0, v1, r1
# CHECK-NEXT: vredminu.b{{[ \t]+}}p0, [r3], r1
# xxlong.vredminu.v221
vredminu.b p0, [r3], r1
# CHECK-NEXT: vredor.b{{[ \t]+}}p0, v1, r1
# extralong.vredor.v124
vredor.b p0, v1, r1
# CHECK-NEXT: vredor.b{{[ \t]+}}p0, [r3], r1
# xxlong.vredor.v225
vredor.b p0, [r3], r1
# CHECK-NEXT: vredxor.b{{[ \t]+}}p0, v1, r1
# extralong.vredxor.v125
vredxor.b p0, v1, r1
# CHECK-NEXT: vredxor.b{{[ \t]+}}p0, [r3], r1
# xxlong.vredxor.v226
vredxor.b p0, [r3], r1
# CHECK-NEXT: vrevbyte.w{{[ \t]+}}p0, v1
# long.vrevbyte.v37
vrevbyte.w p0, v1
# CHECK-NEXT: vrevbyte.w{{[ \t]+}}p0, [r3], v1
# xxlong.vrevbyte.v200
vrevbyte.w p0, [r3], v1
# CHECK-NEXT: vrevbyte.w{{[ \t]+}}p0, v1, [r3]
# xxlong.vrevbyte.v201
vrevbyte.w p0, v1, [r3]
# CHECK-NEXT: vrol.b{{[ \t]+}}p0, v1, v2
# extralong.vrol.v66
vrol.b p0, v1, v2
# CHECK-NEXT: vrol.b{{[ \t]+}}p0, 1, v1
# extralong.vrol.v110
vrol.b p0, 1, v1
# CHECK-NEXT: vrol.b{{[ \t]+}}p0, [r3], v1
# xxlong.vrol.v172
vrol.b p0, [r3], v1
# CHECK-NEXT: vrol.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vrol.v173
vrol.b p0, v1, [r3]
# CHECK-NEXT: vrol.b{{[ \t]+}}p0, 1, [r3]
# xxlong.vrol.v217
vrol.b p0, 1, [r3]
# CHECK-NEXT: vror.b{{[ \t]+}}p0, v1, v2
# extralong.vror.v67
vror.b p0, v1, v2
# CHECK-NEXT: vror.b{{[ \t]+}}p0, 1, v1
# extralong.vror.v111
vror.b p0, 1, v1
# CHECK-NEXT: vror.b{{[ \t]+}}p0, [r3], v1
# xxlong.vror.v174
vror.b p0, [r3], v1
# CHECK-NEXT: vror.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vror.v175
vror.b p0, v1, [r3]
# CHECK-NEXT: vror.b{{[ \t]+}}p0, 1, [r3]
# xxlong.vror.v218
vror.b p0, 1, [r3]
# CHECK-NEXT: vfround.h{{[ \t]+}}p0, v1
# long.vfround.v39
vfround.h p0, v1
# CHECK-NEXT: vfround.h{{[ \t]+}}p0, [r3], v1
# xxlong.vfround.v204
vfround.h p0, [r3], v1
# CHECK-NEXT: vfround.h{{[ \t]+}}p0, v1, [r3]
# xxlong.vfround.v205
vfround.h p0, v1, [r3]
# CHECK-NEXT: vsar.b{{[ \t]+}}p0, v1, v2
# extralong.vsar.v65
vsar.b p0, v1, v2
# CHECK-NEXT: vsar.b{{[ \t]+}}p0, 1, v1
# extralong.vsar.v109
vsar.b p0, 1, v1
# CHECK-NEXT: vsar.b{{[ \t]+}}p0, [r3], v1
# xxlong.vsar.v170
vsar.b p0, [r3], v1
# CHECK-NEXT: vsar.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vsar.v171
vsar.b p0, v1, [r3]
# CHECK-NEXT: vsar.b{{[ \t]+}}p0, 1, [r3]
# xxlong.vsar.v216
vsar.b p0, 1, [r3]
# CHECK-NEXT: vscatter.b{{[ \t]+}}p0, p1, v1, [r1 + r2]
# xxlong.vscatter.v248
vscatter.b p0, p1, v1, [r1 + r2]
# CHECK-NEXT: vscatter.l{{[ \t]+}}p0, p1, v1, [v1]
# xxlong.vscatter.v249
vscatter.l p0, p1, v1, [v1]
# CHECK-NEXT: vscatter.q{{[ \t]+}}p0, p1, v1, [v2]
# xxlong.vscatter.v250
vscatter.q p0, p1, v1, [v2]
# CHECK-NEXT: vscatter.b{{[ \t]+}}p0, p1, v1, [r1 + v2]
# xxlong.vscatter.v251
vscatter.b p0, p1, v1, [r1 + v2]
# CHECK-NEXT: vscatter.b{{[ \t]+}}p0, p1, v1, [r1 + v2 * 1]
# xxlong.vscatter.v252
vscatter.b p0, p1, v1, [r1 + v2 * 1]
# CHECK-NEXT: vscatter.b{{[ \t]+}}p0, p1, v1, [r1 + v2 * 1 + 1]
# xxlong.vscatter.v253
vscatter.b p0, p1, v1, [r1 + v2 * 1 + 1]
# CHECK-NEXT: vscatter.b{{[ \t]+}}p0, p1, v1, [r1 + v2 * 1 + 1]
# xxlong.vscatter.v254
vscatter.b p0, p1, v1, [r1 + v2 * 1 + 1]
# CHECK-NEXT: vscatter.b{{[ \t]+}}p0, p1, v1, [r1 + v2 * 1 + 1]
# xxlong.vscatter.v255
vscatter.b p0, p1, v1, [r1 + v2 * 1 + 1]
# CHECK-NEXT: vscatter.b{{[ \t]+}}p0, p1, v1, [r1 + v2 * 1 + 1]
# xxlong.vscatter.v256
vscatter.b p0, p1, v1, [r1 + v2 * 1 + 1]
# CHECK-NEXT: vshl.b{{[ \t]+}}p0, v1, v2
# extralong.vshl.v63
vshl.b p0, v1, v2
# CHECK-NEXT: vshl.b{{[ \t]+}}p0, 1, v1
# extralong.vshl.v107
vshl.b p0, 1, v1
# CHECK-NEXT: vshl.b{{[ \t]+}}p0, [r3], v1
# xxlong.vshl.v166
vshl.b p0, [r3], v1
# CHECK-NEXT: vshl.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vshl.v167
vshl.b p0, v1, [r3]
# CHECK-NEXT: vshl.b{{[ \t]+}}p0, 1, [r3]
# xxlong.vshl.v214
vshl.b p0, 1, [r3]
# CHECK-NEXT: vshr.b{{[ \t]+}}p0, v1, v2
# extralong.vshr.v64
vshr.b p0, v1, v2
# CHECK-NEXT: vshr.b{{[ \t]+}}p0, 1, v1
# extralong.vshr.v108
vshr.b p0, 1, v1
# CHECK-NEXT: vshr.b{{[ \t]+}}p0, [r3], v1
# xxlong.vshr.v168
vshr.b p0, [r3], v1
# CHECK-NEXT: vshr.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vshr.v169
vshr.b p0, v1, [r3]
# CHECK-NEXT: vshr.b{{[ \t]+}}p0, 1, [r3]
# xxlong.vshr.v215
vshr.b p0, 1, [r3]
# CHECK-NEXT: vslice.b{{[ \t]+}}p0, v1, 1, v2
# extralong.vslice.v106
vslice.b p0, v1, 1, v2
# CHECK-NEXT: vslidedn.b{{[ \t]+}}p0, 1, v1
# extralong.vslidedn.v113
vslidedn.b p0, 1, v1
# CHECK-NEXT: vslideup.b{{[ \t]+}}p0, 1, v1
# extralong.vslideup.v112
vslideup.b p0, 1, v1
# CHECK-NEXT: vfsqrt.h{{[ \t]+}}p0, v1
# long.vfsqrt.v38
vfsqrt.h p0, v1
# CHECK-NEXT: vfsqrt.h{{[ \t]+}}p0, [r3], v1
# xxlong.vfsqrt.v202
vfsqrt.h p0, [r3], v1
# CHECK-NEXT: vfsqrt.h{{[ \t]+}}p0, v1, [r3]
# xxlong.vfsqrt.v203
vfsqrt.h p0, v1, [r3]
# CHECK-NEXT: vsub.b{{[ \t]+}}p0, v1, v2
# extralong.vsub.v51
vsub.b p0, v1, v2
# CHECK-NEXT: vsub.b{{[ \t]+}}p0, [r3], v1
# xxlong.vsub.v142
vsub.b p0, [r3], v1
# CHECK-NEXT: vsub.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vsub.v143
vsub.b p0, v1, [r3]
# CHECK-NEXT: vfsub.h{{[ \t]+}}p0, v1, v2
vfsub.h p0, v1, v2
# CHECK-NEXT: vfsub.h{{[ \t]+}}p0, [r3], v1
vfsub.h p0, [r3], v1
# CHECK-NEXT: vfsub.h{{[ \t]+}}p0, v1, [r3]
vfsub.h p0, v1, [r3]
# CHECK-NEXT: vtestnz.b{{[ \t]+}}p0, v1, v2, p1
# extralong.vtestnz.v49
vtestnz.b p0, v1, v2, p1
# CHECK-NEXT: vtestnz.b{{[ \t]+}}p0, v1, [r3], p1
# xxlong.vtestnz.v232
vtestnz.b p0, v1, [r3], p1
# CHECK-NEXT: vtestz.b{{[ \t]+}}p0, v1, v2, p1
# extralong.vtestz.v48
vtestz.b p0, v1, v2, p1
# CHECK-NEXT: vtestz.b{{[ \t]+}}p0, v1, [r3], p1
# xxlong.vtestz.v231
vtestz.b p0, v1, [r3], p1
# CHECK-NEXT: vtrnhi.b{{[ \t]+}}p0, v1, v2
# extralong.vtrnhi.v98
vtrnhi.b p0, v1, v2
# CHECK-NEXT: vtrnlo.b{{[ \t]+}}p0, v1, v2
# extralong.vtrnlo.v97
vtrnlo.b p0, v1, v2
# CHECK-NEXT: vftrunc.h{{[ \t]+}}p0, v1
# long.vftrunc.v40
vftrunc.h p0, v1
# CHECK-NEXT: vftrunc.h{{[ \t]+}}p0, [r3], v1
# xxlong.vftrunc.v206
vftrunc.h p0, [r3], v1
# CHECK-NEXT: vftrunc.h{{[ \t]+}}p0, v1, [r3]
# xxlong.vftrunc.v207
vftrunc.h p0, v1, [r3]
# CHECK-NEXT: vtruncb.w{{[ \t]+}}p0, v1, v2
# extralong.vtruncb.v78
vtruncb.w p0, v1, v2
# CHECK-NEXT: vtruncl.q{{[ \t]+}}p0, v1, v2
# extralong.vtruncl.v80
vtruncl.q p0, v1, v2
# CHECK-NEXT: vtruncw.l{{[ \t]+}}p0, v1, v2
# extralong.vtruncw.v79
vtruncw.l p0, v1, v2
# CHECK-NEXT: vuziphi.b{{[ \t]+}}p0, v1, v2
# extralong.vuziphi.v96
vuziphi.b p0, v1, v2
# CHECK-NEXT: vuziplo.b{{[ \t]+}}p0, v1, v2
# extralong.vuziplo.v95
vuziplo.b p0, v1, v2
# CHECK-NEXT: vxor.b{{[ \t]+}}p0, v1, v2
# extralong.vxor.v55
vxor.b p0, v1, v2
# CHECK-NEXT: vxor.b{{[ \t]+}}p0, [r3], v1
# xxlong.vxor.v150
vxor.b p0, [r3], v1
# CHECK-NEXT: vxor.b{{[ \t]+}}p0, v1, [r3]
# xxlong.vxor.v151
vxor.b p0, v1, [r3]
# CHECK-NEXT: vziphi.b{{[ \t]+}}p0, v1, v2
# extralong.vziphi.v94
vziphi.b p0, v1, v2
# CHECK-NEXT: vziplo.b{{[ \t]+}}p0, v1, v2
# extralong.vziplo.v93
vziplo.b p0, v1, v2
